import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { it } from 'vitest'

const PROJECT_PAGE_FILE = resolve(process.cwd(), 'app/pages/team/[teamId]/project/[projectId].vue')
const WORKSPACE_MAIN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanel.vue')
const AVATAR_STACK_FILE = resolve(process.cwd(), 'app/components/workspace/collab/CollabPresenceAvatarStack.vue')
const TLDRAW_CANVAS_FILE = resolve(process.cwd(), 'app/components/workspace/collab/WorkspaceTldrawCanvas.client.vue')
const PRESENCE_HELPER_FILE = resolve(process.cwd(), 'app/components/workspace/collab/presence.ts')
const USE_COLLAB_SESSION_FILE = resolve(process.cwd(), 'app/composables/useCollabSession.ts')
const USE_WORKSPACE_REALTIME_FILE = resolve(process.cwd(), 'app/composables/useWorkspaceRealtime.ts')
const REALTIME_WS_FILE = resolve(process.cwd(), 'server/api/realtime/ws.get.ts')
const REALTIME_HUB_FILE = resolve(process.cwd(), 'server/utils/realtime-hub.ts')
const REALTIME_EVENTS_FILE = resolve(process.cwd(), 'server/utils/realtime-events.ts')
const REALTIME_PG_BUS_FILE = resolve(process.cwd(), 'server/plugins/realtime-pg-bus.ts')

it('draw 协作头像栈挂到 breadcrumb 行，并复用用户级聚合数据', async () => {
  const projectPageSource = await readFile(PROJECT_PAGE_FILE, 'utf8')
  const panelSource = await readFile(WORKSPACE_MAIN_PANEL_FILE, 'utf8')
  const canvasSource = await readFile(TLDRAW_CANVAS_FILE, 'utf8')
  const avatarStackSource = await readFile(AVATAR_STACK_FILE, 'utf8')
  const presenceHelperSource = await readFile(PRESENCE_HELPER_FILE, 'utf8')

  assert.match(projectPageSource, /:current-user-id="me\?\.user\.id \|\| ''"/, '项目页未向主面板透传当前用户 ID')
  assert.match(projectPageSource, /:current-user-name="me\?\.user\.username \|\| ''"/, '项目页未向主面板透传当前用户名')
  assert.match(projectPageSource, /:collab-markdown-awareness="collabMarkdownAwareness"/, '项目页未向主面板透传 markdown Awareness')
  assert.match(panelSource, /import CollabPresenceAvatarStack from/, '主面板未接入头像栈组件')
  assert.doesNotMatch(panelSource, /import CollabPresenceDock from/, '主面板仍然保留 markdown 底部成员栏组件')
  assert.match(panelSource, /const collabPresenceUsers = computed<WorkspaceCollabPresenceUser\[\]>\(\(\) => \{/, '主面板未聚合用户级在线成员数据')
  assert.match(panelSource, /const showBreadcrumbPresence = computed\(\(\) => \{/, '主面板未声明 breadcrumb 协作头像显示条件')
  assert.equal((panelSource.match(/<CollabPresenceAvatarStack/g) || []).length, 1, '主面板头像栈应仅保留 breadcrumb 一处入口')
  assert.match(panelSource, /class="text-\[10px\] text-slate-400 px-3 py-1\.5 border-b border-slate-200 bg-white flex gap-2 items-center justify-between"/, 'breadcrumb 行未压缩高度与间距')
  assert.match(panelSource, /<div v-if="showBreadcrumbPresence" class="shrink-0">\s*<CollabPresenceAvatarStack[\s\S]*:users="collabPresenceUsers"[\s\S]*appearance="flat"[\s\S]*size="sm"/, 'breadcrumb 右侧未挂载紧凑协作头像栈')
  assert.doesNotMatch(panelSource, /:presence-users="collabPresenceUsers"/g, '流程画布与自由画布仍把头像栈数据下发给画布 overlay')
  assert.doesNotMatch(panelSource, /<CollabPresenceDock\s+:users="collabPresenceUsers"\s*\/>/, 'markdown 底部成员栏仍然存在')
  assert.doesNotMatch(panelSource, /v-if="hasFlowResource" class="grid grid-cols-1 h-full md:grid-cols-\[1fr,220px\]"/, '流程画布仍保留旧双列在线成员布局')
  assert.doesNotMatch(panelSource, /v-else-if="activePreviewMode === 'draw'"[\s\S]*grid grid-cols-1 h-full md:grid-cols-\[1fr,220px\]/, '自由画布仍保留旧双列在线成员布局')
  assert.doesNotMatch(panelSource, /CollabPresencePanel/, '主面板仍保留旧的右侧在线成员列组件')
  assert.doesNotMatch(panelSource, /<div v-else-if="activeTabId === 'flow'"[\s\S]*flowPanelTitle/, '流程画布仍保留顶部标题栏')
  assert.doesNotMatch(panelSource, /<template v-else-if="activePreviewMode === 'draw'">[\s\S]*rev \{\{ Math\.max\(0, Number\(collabRevision \|\| 0\)\) \}\}/, '自由画布仍保留顶部 rev 栏')
  assert.doesNotMatch(panelSource, /<template v-else-if="activePreviewMode === 'draw'">[\s\S]*<CollabPresenceAvatarStack\s+:users="collabPresenceUsers"\s*\/>/, '自由画布仍在 header 内联渲染头像栈')

  assert.match(avatarStackSource, /data-testid="collab-presence-avatar-stack"/, '头像栈组件缺少稳定测试锚点')
  assert.match(avatarStackSource, /mode\?: StackMode/, '头像栈组件未暴露 overlay 模式开关')
  assert.match(avatarStackSource, /size\?: AvatarStackSize/, '头像栈组件未暴露尺寸变体')
  assert.match(avatarStackSource, /appearance\?: AvatarStackAppearance/, '头像栈组件未暴露外观变体')
  assert.match(avatarStackSource, /const isSmallSize = computed\(\(\) => props\.size === 'sm'\)/, '头像栈未识别紧凑尺寸')
  assert.match(avatarStackSource, /const isFlatAppearance = computed\(\(\) => props\.appearance === 'flat'\)/, '头像栈未识别平面化外观')
  assert.match(avatarStackSource, /resolveAvatarWidth\(\): number \{/, '头像栈未抽离尺寸宽度计算')
  assert.match(avatarStackSource, /resolveAvatarOverlapOffset\(\): number \{/, '头像栈未按尺寸缩放重叠偏移')
  assert.match(avatarStackSource, /shadow-none/, '头像栈未提供无阴影平面样式')
  assert.match(avatarStackSource, /resolveCanvasRoot\(\): HTMLElement \| null \{/, '头像栈组件未接入画布容器定位')
  assert.match(avatarStackSource, /COLLISION_SELECTORS = \[/, '头像栈组件未声明碰撞规避目标区域')
  assert.match(avatarStackSource, /overflowCount = computed\(\(\) => Math\.max\(0, props\.users\.length - visibleUsers\.value\.length\)\)/, '头像栈未处理超出数量折叠')
  assert.match(avatarStackSource, /user\.activityState === 'background' \? 'grayscale\(1\)' : 'none'/, '头像栈未对后台成员做灰化处理')
  assert.match(avatarStackSource, /@mouseenter="openPopover\(user\.userId, \$event\.currentTarget\)"/, '头像栈未改为 hover 打开详情')
  assert.match(avatarStackSource, /<Teleport to="body">/, '头像栈详情层未提升到 body 顶层')
  assert.doesNotMatch(avatarStackSource, /hover:-translate-y-0\.5/, '头像栈仍保留 hover 位移动效')
  assert.doesNotMatch(avatarStackSource, /rounded-full border border-white/, '状态点仍保留白色边框')

  assert.doesNotMatch(canvasSource, /<CollabPresenceAvatarStack[\s\S]*mode="overlay"/, '画布组件仍以内嵌 overlay 模式渲染头像栈')

  assert.match(presenceHelperSource, /export interface WorkspaceCollabPresenceUser \{/, '共享 presence 用户模型缺失')
  assert.match(presenceHelperSource, /selection\?: WorkspaceCollabSelectionSummary \| null/, '共享 presence 用户模型未扩展选区摘要')
  assert.match(presenceHelperSource, /export interface WorkspaceCollabSelectionSummary \{/, '共享选区摘要类型缺失')
  assert.match(presenceHelperSource, /export function resolveWorkspaceCollabPresenceColor/, '共享用户颜色映射缺失')
  assert.match(presenceHelperSource, /return resolveAvatarFallbackValue\(username\)/, '头像 fallback 未复用现有统一规则')
})

it('draw 协作画布展示不同用户的实时彩色鼠标', async () => {
  const projectPageSource = await readFile(PROJECT_PAGE_FILE, 'utf8')
  const panelSource = await readFile(WORKSPACE_MAIN_PANEL_FILE, 'utf8')
  const canvasSource = await readFile(TLDRAW_CANVAS_FILE, 'utf8')
  const collabSessionSource = await readFile(USE_COLLAB_SESSION_FILE, 'utf8')
  const presenceHelperSource = await readFile(PRESENCE_HELPER_FILE, 'utf8')

  assert.match(projectPageSource, /collabSession\.updatePresenceCursor\(value\.cursorX, value\.cursorY\)/, '项目页未把画布鼠标事件回传到协作会话')
  assert.equal((panelSource.match(/:remote-cursors="collabPresenceCursors"/g) || []).length, 2, '流程画布与自由画布未同时接入远端鼠标数据')
  assert.equal((panelSource.match(/@update-collab-cursor="onCollabCursorUpdate"/g) || []).length, 2, '主面板未接收画布鼠标更新事件')
  assert.match(panelSource, /const collabPresenceCursors = computed<WorkspaceCollabCursorUser\[\]>\(\(\) => \{/, '主面板未按用户聚合远端鼠标数据')

  assert.match(canvasSource, /import type \{ WorkspaceCollabCursorUser(?:, WorkspaceCollabPresenceUser)? \}/, '画布组件未声明远端鼠标类型')
  assert.match(canvasSource, /editor\.screenToPage\(\{/, '画布组件未将本地鼠标转换到画布世界坐标')
  assert.match(canvasSource, /editor\.pageToScreen\(\{/, '画布组件未将远端鼠标转换回当前视口坐标')
  assert.match(canvasSource, /data-testid="collab-cursor-overlay"/, '画布组件缺少远端鼠标叠层')
  assert.match(canvasSource, /label: isNearLocalPointer \|\| isNearAnotherCursor\s+\? resolveWorkspaceCollabPresenceInitial\(cursor\.username\)\s+: cursor\.username/, '远端鼠标未实现近距离缩写、默认全称策略')
  assert.match(canvasSource, /localPointerScreen = ref<\{ x: number, y: number \} \| null>\(null\)/, '画布组件未缓存本地鼠标屏幕坐标')
  assert.match(canvasSource, /isNearLocalPointer = Boolean\(/, '画布组件未根据本地鼠标距离切换标签')
  assert.match(canvasSource, /isNearAnotherCursor = cursors\.some\(/, '画布组件未根据远端鼠标彼此距离切换标签')
  assert.match(canvasSource, /editor\.updateViewportScreenBounds\(wrapperRef\.value, center\)/, '画布组件未主动同步 tldraw viewport 边界')
  assert.match(canvasSource, /new ResizeObserver\(\(\) => \{[\s\S]*scheduleViewportScreenBoundsSync\(\)/, '画布组件未在容器尺寸变化后重算 viewport')
  assert.match(canvasSource, /incomingRevision <= lastAppliedIncomingRevision/, '画布组件未按 revision 去重远端 snapshot 回灌')

  assert.match(collabSessionSource, /function updatePresenceCursor\(cursorX\?: number, cursorY\?: number\): void \{/, '协作会话未提供鼠标 presence 更新接口')
  assert.match(collabSessionSource, /input\.workspaceRealtime\.updatePresence\(\{\s+projectId,\s+resourceId,\s+cursorX: pendingCursor\.cursorX,\s+cursorY: pendingCursor\.cursorY,/, '协作会话未把鼠标坐标写入 realtime presence')
  assert.match(presenceHelperSource, /export interface WorkspaceCollabCursorUser \{/, '共享远端鼠标类型缺失')
})

it('presence 通路支持 activityState，并在前端按可见性同步', async () => {
  const collabSessionSource = await readFile(USE_COLLAB_SESSION_FILE, 'utf8')
  const realtimeSource = await readFile(USE_WORKSPACE_REALTIME_FILE, 'utf8')
  const wsSource = await readFile(REALTIME_WS_FILE, 'utf8')
  const hubSource = await readFile(REALTIME_HUB_FILE, 'utf8')
  const eventsSource = await readFile(REALTIME_EVENTS_FILE, 'utf8')
  const pgBusSource = await readFile(REALTIME_PG_BUS_FILE, 'utf8')

  assert.match(collabSessionSource, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/, '协作会话未监听页面可见性变化')
  assert.match(collabSessionSource, /activityState: normalizeWorkspaceCollabPresenceActivityState\(record\.activityState\)/, '协作会话未解析 activityState')
  assert.match(collabSessionSource, /input\.workspaceRealtime\.updatePresence\(\{\s+projectId,\s+resourceId,\s+activityState,\s+\}\)/, '协作会话未回传前后台状态')

  assert.match(realtimeSource, /activityState\?: 'active' \| 'background'/, '前端 realtime 客户端未扩展 activityState 类型')
  assert.match(realtimeSource, /activityState: input\.activityState === 'background' \? 'background' : 'active'/, '前端 realtime 客户端未发送 activityState')

  assert.match(wsSource, /const activityState = normalizeString\(parsedMessage\.payload\?\.activityState\) === 'background'/, 'WS 接口未读取 activityState')
  assert.match(hubSource, /activityState: 'active' \| 'background'/, 'Realtime hub presence 类型未扩展 activityState')
  assert.match(hubSource, /activityState \|\| currentPresence\?\.activityState \|\| 'active'/, 'Realtime hub 未在 presence 更新时保留活动状态')
  assert.match(eventsSource, /activityState: 'active' \| 'background'/, 'Realtime 事件 payload 未扩展 activityState')
  assert.match(pgBusSource, /activityState: normalizeString\(member\.activityState\) === 'background' \? 'background' : 'active'/, 'PG 总线未透传 activityState')
})

it('markdown 协同 presence 通路支持 awareness 快照转发', async () => {
  const collabSessionSource = await readFile(USE_COLLAB_SESSION_FILE, 'utf8')
  const realtimeSource = await readFile(USE_WORKSPACE_REALTIME_FILE, 'utf8')
  const wsSource = await readFile(REALTIME_WS_FILE, 'utf8')
  const hubSource = await readFile(REALTIME_HUB_FILE, 'utf8')
  const eventsSource = await readFile(REALTIME_EVENTS_FILE, 'utf8')
  const pgBusSource = await readFile(REALTIME_PG_BUS_FILE, 'utf8')

  assert.match(collabSessionSource, /const markdownAwareness = computed\(\(\) => \{/, '协作会话未暴露 markdown Awareness')
  assert.match(collabSessionSource, /encodeAwarenessUpdate\(awareness, changedClientIds\)/, '协作会话未编码本地 awareness 更新')
  assert.match(collabSessionSource, /applyAwarenessUpdate\(awareness, awarenessUpdate, 'remote-snapshot'\)/, '协作会话未应用远端 awareness 快照')
  assert.match(collabSessionSource, /removeAwarenessStates\(awareness, staleClientIds, 'remote-snapshot'\)/, '协作会话未清理离线成员 awareness')

  assert.match(realtimeSource, /awarenessClientId\?: number/, '前端 realtime 客户端未扩展 awarenessClientId')
  assert.match(realtimeSource, /awarenessUpdateBase64\?: string/, '前端 realtime 客户端未扩展 awarenessUpdateBase64')
  assert.match(realtimeSource, /awarenessUpdateBase64: normalizeString\(input\.awarenessUpdateBase64\) \|\| undefined/, '前端 realtime 客户端未发送 awareness 快照')

  assert.match(wsSource, /const awarenessClientId = Number\(parsedMessage\.payload\?\.awarenessClientId\)/, 'WS 接口未读取 awarenessClientId')
  assert.match(wsSource, /const awarenessUpdateBase64 = normalizeString\(parsedMessage\.payload\?\.awarenessUpdateBase64\)/, 'WS 接口未读取 awarenessUpdateBase64')
  assert.match(hubSource, /awarenessClientId\?: number/, 'Realtime hub presence 类型未扩展 awarenessClientId')
  assert.match(hubSource, /awarenessUpdateBase64\?: string/, 'Realtime hub presence 类型未扩展 awarenessUpdateBase64')
  assert.match(eventsSource, /awarenessClientId\?: number/, 'Realtime 事件 payload 未扩展 awarenessClientId')
  assert.match(eventsSource, /awarenessUpdateBase64\?: string/, 'Realtime 事件 payload 未扩展 awarenessUpdateBase64')
  assert.match(pgBusSource, /awarenessUpdateBase64: normalizeString\(member\.awarenessUpdateBase64\) \|\| undefined/, 'PG 总线未透传 awareness 快照')
})
