import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { it } from 'vitest'

const PROJECT_PAGE_FILE = resolve(process.cwd(), 'app/pages/team/[teamId]/project/[projectId].vue')
const USE_COLLAB_SESSION_FILE = resolve(process.cwd(), 'app/composables/useCollabSession.ts')
const WORKSPACE_MAIN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanel.vue')
const RICH_TEXT_EDITOR_FILE = resolve(process.cwd(), 'app/components/editor/RichTextEditor.vue')
const RICH_TEXT_COMMANDS_FILE = resolve(process.cwd(), 'app/components/editor/rich-text-editor-commands.ts')

it('项目页使用 useCollabSession 统一协作状态机', async () => {
  const source = await readFile(PROJECT_PAGE_FILE, 'utf8')
  const collabSessionSource = await readFile(USE_COLLAB_SESSION_FILE, 'utf8')
  assert.match(source, /useCollabSession\(/, '项目页未接入 useCollabSession')
  assert.match(source, /collabSession\.handleRealtimeEnvelope\(message\)/, '项目页未复用协作实时消息处理')
  assert.match(source, /collabSession\.activateRoom\(\)/, '项目页未复用协作会话激活逻辑')
  assert.match(source, /const collabMarkdownDoc = collabSession\.markdownDoc/, '项目页未透传 markdown Y.Doc')
  assert.match(source, /const collabMarkdownAwareness = collabSession\.markdownAwareness/, '项目页未透传 markdown Awareness')
  assert.match(source, /:collab-markdown-doc="collabMarkdownDoc"/, '主面板未接入 markdown 文档对象')
  assert.match(source, /:collab-markdown-awareness="collabMarkdownAwareness"/, '主面板未接入 markdown Awareness')
  assert.doesNotMatch(source, /update:collab-markdown-value/, '项目页仍保留旧的 Markdown 文本双向绑定')
  assert.doesNotMatch(source, /function startCollabSnapshotPollTimer/, '项目页仍保留旧的页面级轮询实现')

  assert.match(collabSessionSource, /const markdownDoc = computed\(\(\) => \{/, 'useCollabSession 未暴露 markdownDoc 计算属性')
  assert.match(collabSessionSource, /const markdownAwareness = computed\(\(\) => \{/, 'useCollabSession 未暴露 markdown Awareness 计算属性')
  assert.match(collabSessionSource, /ensureMarkdownCollabDocShape\(doc\)/, 'useCollabSession 未对 markdown 文档执行结构化迁移')
  assert.match(collabSessionSource, /syncMarkdownMirrorFromRichText\(doc\)/, 'useCollabSession 未维护 markdown 镜像同步')
})

it('markdown 协作文档已切换为公共富文本编辑器，旧双栏预览已移除', async () => {
  const panelSource = await readFile(WORKSPACE_MAIN_PANEL_FILE, 'utf8')
  const editorSource = await readFile(RICH_TEXT_EDITOR_FILE, 'utf8')
  const commandsSource = await readFile(RICH_TEXT_COMMANDS_FILE, 'utf8')
  const markdownSection = panelSource.match(/<template v-if="activePreviewMode === 'markdown'">([\s\S]*?)<\/template>/)?.[1] || ''

  assert.match(panelSource, /if \(activeResourceTab\.value\.previewMode === 'markdown'\)\s+return \['项目资料', title\]/, 'markdown breadcrumb 仍然挂在竞赛分析下')
  assert.match(panelSource, /<RichTextEditor[\s\S]*:doc="collabMarkdownDoc"/, '主面板未接入公共富文本编辑器')
  assert.ok(markdownSection, '未找到 markdown 预览分支模板')
  assert.match(panelSource, /:awareness="collabMarkdownAwareness"/, '主面板未向富文本编辑器传入 Awareness')
  assert.match(panelSource, /:current-user="collabCurrentUser"/, '主面板未向富文本编辑器传入当前用户信息')
  assert.match(panelSource, /:show-toolbar="false"/, 'markdown 仍然显示顶部工具栏')
  assert.match(panelSource, /:enable-slash-menu="true"/, 'markdown 未启用 slash 菜单')
  assert.match(panelSource, /:image-upload-handler="markdownImageUploadHandler"/, 'markdown 未接入图片上传处理器')
  assert.match(panelSource, /:heading-levels="\[1, 2, 3, 4, 5, 6\]"/, 'markdown 未将标题能力扩展到 H1-H6')
  assert.match(panelSource, /:ui-font-size-preset="workspaceDisplayPreferenceState\.effective\.fontSizePreset \|\| 'md'"/, 'markdown 未将项目区字体设置透传给编辑器浮层')
  assert.match(panelSource, /content-max-width="1040px"/, 'markdown 未限制正文最大宽度')
  assert.match(panelSource, /@selection-change="onMarkdownSelectionChange"/, '主面板未接收 markdown 本地选区事件')
  assert.match(panelSource, /@remote-presence-change="onMarkdownRemotePresenceChange"/, '主面板未接收 markdown 远端选区事件')
  assert.doesNotMatch(markdownSection, /\{\{ activeResourceTab\.title \}\}/, 'markdown 顶部仍然显示文档标题')
  assert.doesNotMatch(markdownSection, /rev \{\{ Math\.max\(0, Number\(collabRevision \|\| 0\)\) \}\}/, 'markdown 顶部仍然显示修订版本')
  assert.doesNotMatch(markdownSection, /collabConnectionText/, 'markdown 分支仍然显示协作连接文案')
  assert.doesNotMatch(markdownSection, /CollabPresenceAvatarStack/, 'markdown 分支仍然保留第二条协作头')
  assert.doesNotMatch(panelSource, /Markdown 渲染预览/, '主面板仍保留旧的 Markdown 预览区')
  assert.doesNotMatch(panelSource, /workspace-markdown-preview__body/, '主面板仍保留旧的 Markdown 样式残留')
  assert.match(panelSource, /<CollabPresenceAvatarStack[\s\S]*:users="collabPresenceUsers"[\s\S]*appearance="flat"[\s\S]*size="sm"/, 'breadcrumb 右侧未接入紧凑头像栈')
  assert.doesNotMatch(panelSource, /<CollabPresenceDock\s+:users="collabPresenceUsers"\s*\/>/, 'markdown 底部成员栏仍然存在')

  assert.match(editorSource, /createCollabMarkdownBaseExtensions\(\)/, '公共编辑器未复用共享 markdown schema 扩展')
  assert.match(editorSource, /Collaboration\.configure\(\{\s+document: doc,\s+field: 'prosemirror',/, '公共编辑器未接入 Yjs 协作片段')
  assert.match(editorSource, /yCursorPlugin\(awareness, \{/, '公共编辑器未接入 yCursorPlugin')
  assert.match(editorSource, /showToolbar\?: boolean/, '公共编辑器未提供工具栏显隐开关')
  assert.match(editorSource, /contentMaxWidth\?: number \| string/, '公共编辑器未提供正文最大宽度配置')
  assert.match(editorSource, /enableSlashMenu\?: boolean/, '公共编辑器未提供 slash 菜单开关')
  assert.match(editorSource, /imageUploadHandler\?: \(\(file: File\) => Promise<RichTextEditorImageUploadResult>\) \| null/, '公共编辑器未暴露图片上传处理器')
  assert.match(editorSource, /v-if="showToolbar"\s+class="rich-text-editor__toolbar"/, '公共编辑器未按显隐开关渲染工具栏')
  assert.match(editorSource, /--rich-text-editor-content-max-width/, '公共编辑器未通过变量限制正文最大宽度')
  assert.match(editorSource, /data-testid="rich-text-editor-selection-toolbar"/, '公共编辑器未渲染选区浮动工具栏')
  assert.match(editorSource, /const selectionToolbarInlineItems = computed\(\(\) => \{/, '公共编辑器未声明选区工具栏命令集')
  assert.match(editorSource, /function syncSelectionToolbar\(\): void \{/, '公共编辑器未同步选区工具栏位置')
  assert.match(editorSource, /material-symbols-outlined/, '公共编辑器未为选区工具栏接入 icon')
  assert.match(editorSource, /flex-wrap: nowrap;/, '公共编辑器的选区工具栏仍可换行')
  assert.match(editorSource, /preferredAbove >= 12[\s\S]*preferredBelow/, '公共编辑器未优先将选区工具栏放到选区外侧')
  assert.match(editorSource, /data-testid="rich-text-editor-outline"/, '公共编辑器未渲染文档内大纲树容器')
  assert.match(editorSource, /data-testid="rich-text-editor-heading-menu"/, '公共编辑器未渲染标题下拉菜单')
  assert.match(editorSource, /data-testid="rich-text-editor-slash-menu"/, '公共编辑器未渲染 slash 菜单浮层')
  assert.match(editorSource, /handlePaste: handleEditorPaste/, '公共编辑器未接入图片粘贴处理')
  assert.match(editorSource, /handleDrop: handleEditorDrop/, '公共编辑器未接入图片拖拽处理')
  assert.match(editorSource, /setCodeBlock\(\{ language: 'plaintext' \}\)/, '公共编辑器未为新建代码块设置默认语言')
  assert.match(editorSource, /insertUploadingImagePlaceholder\(/, '公共编辑器未插入图片上传占位节点')
  assert.match(editorSource, /scrollToOutlineHeading\(/, '公共编辑器未实现大纲跳转联动')
  assert.match(editorSource, /toggleHeadingMenu\(/, '公共编辑器未实现标题下拉交互')

  assert.match(commandsSource, /label: '正文'/, '统一命令注册表缺少正文命令')
  assert.match(commandsSource, /label: `H\$\{level\}`/, '统一命令注册表缺少标题命令')
  assert.match(commandsSource, /resolveHeadingIcon/, '统一命令注册表未为标题补齐 icon')
  assert.match(commandsSource, /label: '图片上传'/, '统一命令注册表缺少图片命令')
  assert.match(commandsSource, /action: 'image'/, '统一命令注册表未定义图片动作')
})

it('画布已升级为真实引擎组件并移除 JSON 文本输入', async () => {
  const source = await readFile(WORKSPACE_MAIN_PANEL_FILE, 'utf8')
  assert.match(source, /<WorkspaceTldrawCanvas[\s\S]*@update:model-value="onCollabDrawModelUpdate"/, '画布未接入 WorkspaceTldrawCanvas 组件')
  assert.doesNotMatch(source, /请输入画布节点 JSON（数组）/, '画布仍暴露 JSON 文本输入入口')
})
