import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { describe, it } from 'vitest'

async function readSource(relativePath) {
  return readFile(resolve(process.cwd(), relativePath), 'utf8')
}

describe('飞书多维表格版本草稿链路', () => {
  it('同步项编辑器仍然使用当前草稿做预检并本地回写保存结果', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')
    const saveBlockMatch = componentSource.match(/async function saveCurrentItem\(saveContext: SaveCurrentItemContext = 'main'\) \{([\s\S]*?)\n\}\n\nasync function toggleItemEnabled/)

    assert.match(componentSource, /const draft: FeishuBitableSyncItemPreviewRequest = \{/, '编辑器没有构造草稿预检请求')
    assert.match(componentSource, /source:\s*\{[\s\S]*appToken:[\s\S]*tableId:[\s\S]*viewId:/, '预检请求缺少来源草稿')
    assert.match(componentSource, /mapping,\s*options,\s*autoSync,\s*writeback,/, '预检请求缺少映射\/选项\/自动同步\/回填草稿')
    assert.match(componentSource, /const autoSync = parseJsonText\(autoSyncDraftText\.value, '自动同步配置'\)/, '预检链路未读取自动同步 Drawer 草稿')
    assert.ok(saveBlockMatch, '未找到同步项保存逻辑')
    const saveBlock = saveBlockMatch[1]
    assert.match(saveBlock, /autoSync = parseJsonText\(autoSyncDraftText\.value, '自动同步配置'\)/, '保存链路未解析自动同步 Drawer 草稿')
    assert.match(saveBlock, /mapping,\s*options,\s*autoSync,\s*writeback,/, '保存链路未提交自动同步草稿')
    assert.match(saveBlock, /applySavedItemLocally\(data\)/, '保存后没有本地回写同步项状态')
    assert.doesNotMatch(saveBlock, /await loadSyncDetail\(/, '保存同步项后不应隐式整页重载')
    assert.doesNotMatch(saveBlock, /await loadItemDetail\(/, '保存同步项后不应再次拉取当前项详情')
  })

  it('竞赛库映射已经统一为时间节点文本，并暴露适配人群字段', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')
    const configSource = await readSource('shared/utils/feishu-bitable-sync-config.ts')
    const serviceSource = await readSource('server/services/feishu/bitable-sync.ts')

    assert.match(componentSource, /timelineText（时间节点）/, '竞赛映射未使用统一时间节点字段')
    assert.match(componentSource, /recommendedFor（适配人群）/, '竞赛映射缺少适配人群字段')
    assert.doesNotMatch(componentSource, /contest:\s*\[[\s\S]*organizer（主办方）[\s\S]*\],\n\s{2}track:/, '竞赛库映射不应暴露主办方字段')
    assert.doesNotMatch(componentSource, /contest:\s*\[[\s\S]*coOrganizer（协办\/承办）[\s\S]*\],\n\s{2}track:/, '竞赛库映射不应暴露协办/承办字段')
    assert.doesNotMatch(componentSource, /contest:\s*\[[\s\S]*participantRequirements（参赛对象）[\s\S]*\],\n\s{2}track:/, '竞赛库映射不应暴露参赛对象字段')
    assert.doesNotMatch(componentSource, /contest:\s*\[[\s\S]*teamRule（组队规则）[\s\S]*\],\n\s{2}track:/, '竞赛库映射不应暴露组队规则字段')
    assert.doesNotMatch(componentSource, /contest:\s*\[[\s\S]*currentSeason（当前届次）[\s\S]*\],\n\s{2}track:/, '竞赛库映射不应暴露当前届次字段')
    assert.match(configSource, /if \(entityType === 'contest'\) \{[\s\S]*timelineText:\s*''[\s\S]*recommendedFor:\s*''/, '竞赛默认模板未切到 timelineText / recommendedFor')
    assert.doesNotMatch(configSource, /if \(entityType === 'contest'\) \{[\s\S]*organizer:\s*''[\s\S]*\n\s{2}if \(entityType === 'track'\)/, '竞赛默认模板不应包含主办方字段')
    assert.doesNotMatch(configSource, /if \(entityType === 'contest'\) \{[\s\S]*(coOrganizer|participantRequirements|teamRule|currentSeason):\s*''[\s\S]*\n\s{2}if \(entityType === 'track'\)/, '竞赛默认模板不应包含飞书竞赛库没有的字段')
    assert.match(serviceSource, /const timelineText = toText\(timelineTextRaw\)[\s\S]*registrationWindow[\s\S]*submissionDeadline/, '竞赛同步未兼容旧时间字段并收敛到 timelineText')
    assert.match(serviceSource, /const timelines = buildContestReleaseTimelines\(input\.externalId, timelineText\)/, '竞赛同步未从统一时间文本构建节点快照')
    assert.doesNotMatch(serviceSource, /async function applyContestRecord[\s\S]*input\.resolver\.getText\('organizer'\)[\s\S]*async function applyTrackRecord/, '竞赛库同步不应读取 organizer')
    assert.doesNotMatch(serviceSource, /async function applyContestRecord[\s\S]*input\.resolver\.getText\('(coOrganizer|participantRequirements|teamRule|currentSeason)'\)[\s\S]*async function applyTrackRecord/, '竞赛库同步不应读取飞书竞赛库没有的字段')
  })

  it('资料库、政策库与人设库映射已经切到当前字段集，并打通新实体链路', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')
    const configSource = await readSource('shared/utils/feishu-bitable-sync-config.ts')
    const serviceSource = await readSource('server/services/feishu/bitable-sync.ts')
    const docsSource = await readSource('app/pages/admin/docs/index.vue')
    const createApiSource = await readSource('server/api/admin/integrations/feishu/bitable-syncs/[id]/items/index.post.ts')
    const patchApiSource = await readSource('server/api/admin/integrations/feishu/bitable-syncs/[id]/items/[itemId].patch.ts')
    const personaImportSource = await readSource('server/api/projects/[id]/defense/personas/import.post.ts')

    assert.match(componentSource, /attachment（附件）/, '资料映射缺少附件字段')
    assert.match(componentSource, /attachmentSummary（附件摘要）/, '资料映射缺少附件摘要字段')
    assert.doesNotMatch(componentSource, /contestRelationInfo（竞赛关联信息文本）/, '资料映射不应再暴露竞赛关联信息文本字段')
    assert.doesNotMatch(componentSource, /trackRelationInfo（赛道关联信息文本）/, '资料映射不应再暴露赛道关联信息文本字段')
    assert.doesNotMatch(configSource, /contestRelationInfo:\s*''/, '资料默认模板不应再包含竞赛关联信息文本字段')
    assert.doesNotMatch(configSource, /trackRelationInfo:\s*''/, '资料默认模板不应再包含赛道关联信息文本字段')
    assert.match(componentSource, /value: 'policy', label: '政策'/, '编辑器未提供政策实体类型')
    assert.match(componentSource, /value: 'persona', label: '人设'/, '编辑器未提供人设实体类型')
    assert.match(componentSource, /externalId（会议编号）/, '政策映射未明确会议编号语义')
    assert.match(componentSource, /meetingName（会议名称）/, '政策映射缺少会议名称字段')
    assert.match(componentSource, /officialMaterialLink（官网资料链接）/, '政策映射缺少官网资料链接字段')
    assert.match(componentSource, /object（对象）/, '人设映射缺少对象字段')
    assert.match(componentSource, /persona1（人设1）/, '人设映射缺少人设1字段')
    assert.match(componentSource, /persona5（人设5）/, '人设映射缺少人设5字段')
    assert.doesNotMatch(componentSource, /judgeType（评委类型）/, '人设映射不应再暴露评委类型字段')
    assert.doesNotMatch(componentSource, /systemPrompt（系统提示词）/, '人设映射不应再暴露系统提示词字段')
    assert.match(configSource, /if \(entityType === 'policy'\) \{[\s\S]*meetingName:\s*''[\s\S]*xiaohongshuMaterialLink:\s*''/, '政策默认模板未补齐完整字段')
    assert.match(configSource, /if \(entityType === 'persona'\) \{[\s\S]*contestExternalIdField:\s*''[\s\S]*object:\s*''[\s\S]*persona1:\s*''[\s\S]*persona5:\s*''/, '人设默认模板未切到对象 + 五槽位字段')
    assert.match(serviceSource, /attachmentSummary/, '资料同步缺少附件摘要字段')
    assert.doesNotMatch(serviceSource, /contestRelationInfo/, '资料同步不应再读取竞赛关联信息文本')
    assert.doesNotMatch(serviceSource, /trackRelationInfo/, '资料同步不应再读取赛道关联信息文本')
    assert.match(serviceSource, /async function applyPolicyRecord\(/, '服务端未接入政策同步')
    assert.match(serviceSource, /政策记录缺少必要字段（externalId 或 meetingName）/, '政策同步仍未要求 externalId 与 meetingName 同时齐备')
    assert.match(serviceSource, /upsertPolicyLibraryReleaseDraft/, '政策同步未写入版本草稿')
    assert.match(serviceSource, /async function applyPersonaRecord\(/, '服务端未接入人设同步')
    assert.match(serviceSource, /upsertDefensePersonaPreset/, '人设同步未写入独立预设存储')
    assert.match(serviceSource, /scope: 'persona'/, '人设同步未回写 persona external ref')
    assert.match(serviceSource, /PERSONA_SLOTS_EMPTY/, '人设同步未识别空槽位整行跳过')
    assert.match(serviceSource, /buildFeishuPersonaSyncDrafts/, '人设同步未按对象 + 槽位派生 preset 草稿')
    assert.match(serviceSource, /listDefensePersonaPresetExternalIdsBySyncItemId/, '人设同步未读取 sync item 级历史 preset 做对齐清理')
    assert.match(serviceSource, /deleteFeishuExternalRefsByExternalIds/, '人设同步未清理历史 persona external ref')
    assert.match(serviceSource, /shouldCleanupFeishuPersonaStaleData/, '人设同步未对零产出场景收紧清理条件')
    assert.match(serviceSource, /skippedCount:\s*Math\.max\(candidateSlotCount,\s*1\)/, '人设缺必要字段时未至少记一次跳过')
    assert.match(serviceSource, /skippedCount:\s*1/, '人设空槽位整行跳过时未计入跳过数')
    assert.match(docsSource, /externalId \/ contestExternalId \/ object \/ persona1~5/, '文档中心未说明新的人设库字段')
    assert.match(docsSource, /比赛类型、具体赛事名或名人等自由文本/, '文档中心未说明对象字段的填写方式')
    assert.match(createApiSource, /'policy'/, '新增同步项接口未接受 policy 实体类型')
    assert.match(createApiSource, /'persona'/, '新增同步项接口未接受 persona 实体类型')
    assert.match(patchApiSource, /'policy'/, '更新同步项接口未接受 policy 实体类型')
    assert.match(patchApiSource, /'persona'/, '更新同步项接口未接受 persona 实体类型')
    assert.match(createApiSource, /entityType 不支持：\$\{rawEntityType\}。/, '新增同步项接口未返回可定位的 entityType 错误')
    assert.match(personaImportSource, /getFeishuExternalRefByEntityId/, '项目导入未先解析 live contest\/track 对应的 external ref')
    assert.match(personaImportSource, /listDefensePersonaPresetsByContestExternalId/, '项目导入未优先读取人设预设存储')
    assert.match(personaImportSource, /pickDefensePersonaPresetsForImport/, '项目导入未按比赛\/赛道收口人设预设')
    assert.match(personaImportSource, /buildDefensePersonaImportDraftsFromPresets/, '项目导入未从人设预设构造项目草稿')
    assert.match(personaImportSource, /return buildContestDefensePersonaDrafts/, '项目导入缺少旧动态人设回退链路')
    assert.match(personaImportSource, /enabled: draft\.enabled/, '项目导入没有保留预设启用状态')
  })

  it('服务端预检与执行都已经围绕 release draft，而不是直接写 live 数据', async () => {
    const serviceSource = await readSource('server/services/feishu/bitable-sync.ts')

    assert.match(serviceSource, /upsertContestReleaseDraft/, '竞赛相关同步未写入 release draft')
    assert.match(serviceSource, /entityId: draft\.version\?\.id \|\| ''/, '同步返回结果未回填 release version id')
    assert.match(serviceSource, /scopeKind: 'contest'/, '竞赛预检未基于 contest release scope 判断')
    assert.match(serviceSource, /upsertPolicyLibraryReleaseDraft/, '政策同步未写入 policy library release draft')
    assert.doesNotMatch(serviceSource, /syncContestDerivedTimelineNodes\(/, '同步链路不应回退到直接写 live 时间节点')
    assert.doesNotMatch(serviceSource, /syncTrackRubric\(/, '同步链路不应回退到直接派生 live rubric')
  })

  it('整理当前实体模板时会清掉历史资料关联文本字段残留', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')
    const configSource = await readSource('shared/utils/feishu-bitable-sync-config.ts')

    assert.match(componentSource, /function buildSupportedMappingTargetKeys\(entityType: FeishuBitableSyncItemEntityType\) \{\s+return new Set\(\(MAPPING_OPTIONS\[entityType\] \|\| \[\]\)\.map\(item => item\.key\)\)\s+\}/, '编辑器未按当前实体类型收敛支持字段')
    assert.match(componentSource, /function normalizeCurrentEntityTemplate\(\) \{[\s\S]*normalizeMappingWizardBindings\(mappingWizardBindings\.value\)[\s\S]*writeMappingWizardToJson\(false\)[\s\S]*已按当前实体类型整理配置，并保留可识别的字段映射/, '整理当前实体模板未回写过滤后的映射配置')
    assert.doesNotMatch(componentSource, /contestRelationInfo（竞赛关联信息文本）/, '资料模板仍暴露旧竞赛关联文本字段')
    assert.doesNotMatch(componentSource, /trackRelationInfo（赛道关联信息文本）/, '资料模板仍暴露旧赛道关联文本字段')
    assert.doesNotMatch(configSource, /contestRelationInfo:\s*''/, '资料默认模板仍保留旧竞赛关联文本字段')
    assert.doesNotMatch(configSource, /trackRelationInfo:\s*''/, '资料默认模板仍保留旧赛道关联文本字段')
    assert.doesNotMatch(componentSource, /judgeType（评委类型）/, '人设模板仍保留旧评委类型字段')
    assert.doesNotMatch(configSource, /judgeType:\s*''/, '人设默认模板仍保留旧评委类型字段')
  })

  it('后台会提示人设同步已抓取源行但零产出的排查方向', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')
    const serviceSource = await readSource('server/services/feishu/bitable-sync.ts')
    const configSource = await readSource('shared/utils/feishu-bitable-sync-config.ts')
    const typeSource = await readSource('shared/types/domain-legacy.ts')
    const schemaSource = await readSource('server/database/bootstrap/schema.ts')
    const storeSource = await readSource('server/utils/feishu-integration-store.ts')

    assert.match(componentSource, /shouldShowPersonaZeroOutputHint/, '编辑器未识别人设零产出执行结果')
    assert.match(componentSource, /PERSONA_ZERO_OUTPUT_HINT/, '编辑器未提供人设零产出提示文案')
    assert.match(componentSource, /PERSONA_SLOTS_EMPTY \/ MISSING_REQUIRED_FIELD/, '编辑器未提示查看关键原因码')
    assert.match(componentSource, /SYNC_RUN_ZERO_FETCH_HINT/, '编辑器未提供零抓取提示文案')
    assert.match(componentSource, /SYNC_RUN_ALL_SKIPPED_HINT/, '编辑器未提供全量跳过提示文案')
    assert.match(componentSource, /function syncRunHintText\(/, '编辑器未统一输出执行结果提示')
    assert.match(componentSource, /guessFeishuBitableFieldName/, '映射 Drawer 未使用共享字段猜测工具')
    assert.match(componentSource, /listRequiredSyncItemFieldGroups/, '编辑器未使用分组必填映射提示')
    assert.match(configSource, /persona1~5 任一槽位/, '人设重点映射提示未改成任一槽位')
    assert.match(componentSource, /重新匹配缺失字段/, '映射 Drawer 缺少重新匹配缺失字段动作')
    assert.match(componentSource, /规则过滤/, '执行日志未展示规则过滤诊断')
    assert.match(componentSource, /业务跳过/, '执行日志未展示业务跳过诊断')
    assert.match(componentSource, /详细诊断/, '执行日志未展示详细诊断区块')
    assert.match(componentSource, /规则过滤样本/, '执行日志未展示规则过滤样本')
    assert.match(componentSource, /业务跳过样本/, '执行日志未展示业务跳过样本')
    assert.match(componentSource, /查看诊断 JSON/, '执行日志未提供诊断 JSON 查看入口')
    assert.match(componentSource, /人设槽位为空/, '预检结果未展示人设槽位为空计数')
    assert.match(componentSource, /computed\(\(\) => 'body'\)/, '编辑器未把选择器弹层挂回 body，可能仍被 Drawer 层级吃掉')
    assert.match(serviceSource, /function buildSummaryBase\(input: \{/, '服务端未支持按原始记录数构建汇总')
    assert.match(serviceSource, /skippedCount:\s*Math\.max\(0,\s*fetchedCount - processedCount\)/, '服务端未把过滤掉的记录计入跳过数')
    assert.match(serviceSource, /sourceRecordCount:\s*records\.length/, '执行链路未透传原始飞书记录数')
    assert.match(serviceSource, /recordBusinessSkipDiagnostics/, '执行链路未记录业务跳过诊断')
    assert.match(serviceSource, /collectAutoSyncRunDiagnostics/, '执行链路未记录自动同步状态分布')
    assert.match(serviceSource, /SYNC_RUN_DIAGNOSTIC_SAMPLE_LIMIT/, '执行链路未限制详细诊断样本数量')
    assert.match(serviceSource, /filteredSamples\.push/, '执行链路未记录规则过滤样本')
    assert.match(serviceSource, /businessSkipSamples/, '执行链路未记录业务跳过样本')
    assert.match(serviceSource, /function normalizeWritebackStatusField/, '执行链路未保护回填状态误写入记录状态字段')
    assert.match(serviceSource, /field === autoSync\.recordStatusField && autoSync\.syncStatusField/, '回填状态字段误指向记录状态时未改写到同步信息')
    assert.match(typeSource, /export interface FeishuBitableSyncRunDiagnostics/, '共享类型未声明执行诊断结构')
    assert.match(typeSource, /filteredSamples\?: Array/, '共享类型未声明规则过滤样本')
    assert.match(typeSource, /businessSkipSamples\?: Array/, '共享类型未声明业务跳过样本')
    assert.match(typeSource, /personaSlotsEmpty: number/, '预检问题计数未细分人设槽位为空')
    assert.match(schemaSource, /diagnostics_json JSONB NOT NULL DEFAULT '\{\}'::JSONB/, 'schema 未持久化同步执行诊断')
    assert.match(storeSource, /diagnostics_json = \$10::JSONB/, '存储层完成执行时未写入诊断')
    assert.match(serviceSource, /contestId: toText\(result\.rows\[0\]\?\.live_entity_id\) \|\| null/, '赛事关联解析仍未改用本地 toText')
    assert.doesNotMatch(serviceSource, /normalizeText\(/, 'bitable-sync 不应再残留未定义的 normalizeText 调用')
  })

  it('同步到实体类型已改成固定按钮组，不再依赖问题下拉', async () => {
    const componentSource = await readSource('app/components/admin/AdminFeishuBitableSyncEditor.vue')

    assert.match(componentSource, /const itemEntityTypeOptions = computed\(\(\) => buildEntityTypeChoiceOptions\(itemForm\.entityType\)\)/, '当前同步项未使用实体类型按钮组选项')
    assert.match(componentSource, /const newItemEntityTypeOptions = computed\(\(\) => buildEntityTypeChoiceOptions\(newItemForm\.entityType\)\)/, '新增同步项未使用实体类型按钮组选项')
    assert.match(componentSource, /function buildEntityTypeChoiceOptions\(currentValue\?: string \| null\)/, '实体类型按钮组选项构建函数缺失')
    assert.match(componentSource, /v-for="option in itemEntityTypeOptions"/, '当前同步项“同步到”未渲染按钮组')
    assert.match(componentSource, /v-for="option in newItemEntityTypeOptions"/, '新增同步项“同步到”未渲染按钮组')
    assert.doesNotMatch(componentSource, /<a-select v-model="itemForm\.entityType"/, '当前同步项“同步到”不应继续使用下拉')
    assert.doesNotMatch(componentSource, /<a-select v-model="newItemForm\.entityType"/, '新增同步项“同步到”不应继续使用下拉')
  })
})
