import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { it } from 'vitest'

const DOMAIN_TYPES_FILE = resolve(process.cwd(), 'shared/types/domain.ts')
const AUTH_TYPES_FILE = resolve(process.cwd(), 'shared/types/auth.ts')
const SCHEMA_FILE = resolve(process.cwd(), 'server/database/bootstrap/schema.ts')
const NOTIFICATION_STORE_FILE = resolve(process.cwd(), 'server/utils/notification-store.ts')
const NOTIFICATION_LIST_API_FILE = resolve(process.cwd(), 'server/api/notifications/index.get.ts')
const NOTIFICATION_READ_ALL_API_FILE = resolve(process.cwd(), 'server/api/notifications/read-all.post.ts')
const ADMIN_NOTIFICATION_API_FILE = resolve(process.cwd(), 'server/api/admin/notifications/index.post.ts')
const TEAM_INVITE_API_FILE = resolve(process.cwd(), 'server/api/teams/[id]/invitations.post.ts')
const PROJECT_INVITE_API_FILE = resolve(process.cwd(), 'server/api/projects/[id]/invitations/index.post.ts')
const INVITE_ACCEPT_API_FILE = resolve(process.cwd(), 'server/api/invitations/[token]/accept.post.ts')
const PLATFORM_STORE_FILE = resolve(process.cwd(), 'server/utils/platform-store.ts')
const TEAM_MEMBERSHIP_STORE_FILE = resolve(process.cwd(), 'server/utils/team-membership-store.ts')
const NOTIFICATION_BELL_FILE = resolve(process.cwd(), 'app/components/notifications/NotificationBellButton.vue')
const NOTIFICATION_DRAWER_FILE = resolve(process.cwd(), 'app/components/notifications/NotificationDrawer.vue')
const NOTIFICATION_COMPOSABLE_FILE = resolve(process.cwd(), 'app/composables/useNotificationCenter.ts')
const DASHBOARD_TOPBAR_FILE = resolve(process.cwd(), 'app/components/dashboard/DashboardTopbar.vue')
const WORKSPACE_HEADER_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceHeader.vue')
const WORKSPACE_LEFT_RAIL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceLeftRail.vue')
const ADMIN_INDEX_FILE = resolve(process.cwd(), 'app/pages/admin/index.vue')
const ADMIN_NOTIFICATIONS_PAGE_FILE = resolve(process.cwd(), 'app/pages/admin/notifications.vue')

it('通知领域类型与 user_notifications 表已落地', async () => {
  const domainSource = await readFile(DOMAIN_TYPES_FILE, 'utf8')
  const authTypesSource = await readFile(AUTH_TYPES_FILE, 'utf8')
  const schemaSource = await readFile(SCHEMA_FILE, 'utf8')

  assert.match(domainSource, /export \* from '\.\/auth'/, 'domain 类型聚合入口未转发 auth 模块')
  assert.match(authTypesSource, /UserNotificationCategory/, '通知分类类型缺失')
  assert.match(authTypesSource, /UserNotificationListResult/, '通知列表返回结构缺失')
  assert.match(schemaSource, /CREATE TABLE IF NOT EXISTS user_notifications \(/, 'user_notifications 表未创建')
  assert.match(schemaSource, /UNIQUE\(user_id, dedupe_key\)/, '通知去重约束缺失')
  assert.match(schemaSource, /idx_user_notifications_user_created/, '通知列表索引缺失')
})

it('通知 store 支持平台下发、比赛提醒与成员变更通知', async () => {
  const source = await readFile(NOTIFICATION_STORE_FILE, 'utf8')

  assert.match(source, /export async function ensureContestDeadlineNotifications\(/, '比赛提醒惰性生成入口缺失')
  assert.match(source, /contest\.deadline_reminder/, '比赛提醒通知类型未接入')
  assert.match(source, /export async function publishPlatformAnnouncement\(/, '平台通知发布函数缺失')
  assert.match(source, /export async function emitProjectMemberMutationNotifications\(/, '项目成员变更通知函数缺失')
  assert.match(source, /export async function emitWorkspaceMemberRemovedNotifications\(/, 'workspace 成员移除通知函数缺失')
})

it('通知 API 与业务写路径已接线', async () => {
  const listApiSource = await readFile(NOTIFICATION_LIST_API_FILE, 'utf8')
  const readAllApiSource = await readFile(NOTIFICATION_READ_ALL_API_FILE, 'utf8')
  const adminApiSource = await readFile(ADMIN_NOTIFICATION_API_FILE, 'utf8')
  const teamInviteApiSource = await readFile(TEAM_INVITE_API_FILE, 'utf8')
  const projectInviteApiSource = await readFile(PROJECT_INVITE_API_FILE, 'utf8')
  const acceptApiSource = await readFile(INVITE_ACCEPT_API_FILE, 'utf8')
  const platformStoreSource = await readFile(PLATFORM_STORE_FILE, 'utf8')
  const teamMembershipSource = await readFile(TEAM_MEMBERSHIP_STORE_FILE, 'utf8')

  assert.match(listApiSource, /ensureContestDeadlineNotifications/, '通知列表接口未接入比赛提醒惰性生成')
  assert.match(listApiSource, /listUserNotifications/, '通知列表接口未接入通知查询')
  assert.match(readAllApiSource, /markAllUserNotificationsRead/, '全部已读接口缺失')
  assert.match(adminApiSource, /publishPlatformAnnouncement/, '管理端通知发布接口缺失')
  assert.match(teamInviteApiSource, /emitInvitationCreatedNotifications/, 'Team 邀请创建未接入通知')
  assert.match(projectInviteApiSource, /emitInvitationCreatedNotifications/, '项目邀请创建未接入通知')
  assert.match(acceptApiSource, /emitInvitationAcceptedNotifications/, '邀请接受未接入通知')
  assert.match(platformStoreSource, /emitProjectMemberMutationNotifications/, '项目成员写路径未接入通知')
  assert.match(teamMembershipSource, /emitWorkspaceMemberRemovedNotifications/, 'workspace 成员移除未接入通知')
})

it('前端已接入共享通知中心抽屉与铃铛入口', async () => {
  const bellSource = await readFile(NOTIFICATION_BELL_FILE, 'utf8')
  const drawerSource = await readFile(NOTIFICATION_DRAWER_FILE, 'utf8')
  const composableSource = await readFile(NOTIFICATION_COMPOSABLE_FILE, 'utf8')
  const dashboardTopbarSource = await readFile(DASHBOARD_TOPBAR_FILE, 'utf8')
  const workspaceHeaderSource = await readFile(WORKSPACE_HEADER_FILE, 'utf8')
  const workspaceLeftRailSource = await readFile(WORKSPACE_LEFT_RAIL_FILE, 'utf8')
  const adminIndexSource = await readFile(ADMIN_INDEX_FILE, 'utf8')
  const adminNotificationsPageSource = await readFile(ADMIN_NOTIFICATIONS_PAGE_FILE, 'utf8')

  assert.match(composableSource, /export function useNotificationCenter\(\)/, '通知中心 composable 缺失')
  assert.match(composableSource, /\/notifications\/read-all/, '通知中心未接入全部已读接口')
  assert.match(composableSource, /POLL_INTERVAL_MS = 60_000/, '通知中心缺少轮询策略')
  assert.match(drawerSource, /variant\?: 'default' \| 'rail'/, '通知抽屉未支持 rail aside 变体')
  assert.match(drawerSource, /title="通知中心"/, '通知抽屉标题缺失')
  assert.match(drawerSource, /v-model:visible="drawerVisible"/, '通知抽屉未通过共享状态受控打开')
  assert.match(drawerSource, /全部已读/, '通知抽屉未提供全部已读入口')
  assert.match(drawerSource, /data-testid="workspace-left-rail-notification-aside"/, 'Workspace 左 rail 通知中心缺少 aside 测试锚点')
  assert.match(drawerSource, /<aside[\s\S]*class="notification-drawer-aside"/, 'Workspace 左 rail 通知中心未改成 aside 承载')
  assert.match(drawerSource, /\.notification-drawer-aside \{[\s\S]*top:\s*0;[\s\S]*bottom:\s*0;[\s\S]*left:\s*100%;/, 'Workspace 左 rail 通知中心未贴 rail 展开')
  assert.match(drawerSource, /width:\s*min\(var\(--workspace-left-panel-width,\s*304px\),\s*calc\(100vw - 108px\)\);/, 'Workspace 左 rail 通知中心未跟随左栏面板宽度')
  assert.match(bellSource, /variant\?: 'default' \| 'rail'/, '通知铃铛未支持 rail 变体')
  assert.match(bellSource, /const \{ drawerVisible, initialized, unreadCount \} = center/, '通知铃铛未复用共享抽屉打开态')
  assert.match(bellSource, /notification-bell-button--rail-active/, '左 rail 通知按钮缺少打开态样式')
  assert.match(bellSource, /emit\('open'\)/, '通知铃铛未暴露打开事件')
  assert.match(bellSource, /if \(drawerVisible\.value\) \{[\s\S]*center\.closeDrawer\(\)/, '通知铃铛再次点击时未切换为关闭')
  assert.match(bellSource, /pointer-events: auto;/, '左 rail 通知标签仍不可点击')
  assert.match(bellSource, /<NotificationDrawer :workspace-id="props\.workspaceId" :variant="props\.variant" \/>/, '铃铛入口未按场景挂载通知抽屉变体')
  assert.match(dashboardTopbarSource, /import NotificationBellButton from '~\/components\/notifications\/NotificationBellButton\.vue'/, 'Dashboard 顶栏未显式导入通知铃铛')
  assert.match(dashboardTopbarSource, /<NotificationBellButton :workspace-id="workspaceId" \/>/, 'Dashboard 顶栏未接入通知铃铛')
  assert.doesNotMatch(workspaceHeaderSource, /NotificationBellButton/, 'Workspace 头部仍保留旧的通知铃铛入口')
  assert.match(workspaceLeftRailSource, /<NotificationBellButton[\s\S]*variant="rail"/, 'Workspace 左 rail 未接入通知铃铛')
  assert.match(workspaceLeftRailSource, /data-testid="workspace-left-rail-notification-button"/, 'Workspace 左 rail 缺少通知入口测试标记')
  assert.match(adminIndexSource, /to="\/admin\/notifications"/, '管理首页缺少通知管理入口')
  assert.match(adminNotificationsPageSource, /通知管理/, '后台独立通知管理页缺失')
  assert.match(adminNotificationsPageSource, /Publish Notification/, '独立通知管理页缺少发布表单')
  assert.match(adminNotificationsPageSource, /\/admin\/notifications/, '独立通知管理页未接入通知发布接口')
})
