import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { it } from 'vitest'

const DOMAIN_TYPES_FILE = resolve(process.cwd(), 'shared/types/domain.ts')
const AUTH_TYPES_FILE = resolve(process.cwd(), 'shared/types/auth.ts')
const SCHEMA_FILE = resolve(process.cwd(), 'server/database/bootstrap/schema.ts')
const NOTIFICATION_STORE_FILE = resolve(process.cwd(), 'server/utils/notification-store.ts')
const NOTIFICATION_LIST_API_FILE = resolve(process.cwd(), 'server/api/notifications/index.get.ts')
const NOTIFICATION_READ_ALL_API_FILE = resolve(process.cwd(), 'server/api/notifications/read-all.post.ts')
const ADMIN_NOTIFICATION_API_FILE = resolve(process.cwd(), 'server/api/admin/notifications/index.post.ts')
const TEAM_INVITE_API_FILE = resolve(process.cwd(), 'server/api/teams/[id]/invitations.post.ts')
const PROJECT_INVITE_API_FILE = resolve(process.cwd(), 'server/api/projects/[id]/invitations/index.post.ts')
const INVITE_ACCEPT_API_FILE = resolve(process.cwd(), 'server/api/invitations/[token]/accept.post.ts')
const PLATFORM_STORE_FILE = resolve(process.cwd(), 'server/utils/platform-store.ts')
const TEAM_MEMBERSHIP_STORE_FILE = resolve(process.cwd(), 'server/utils/team-membership-store.ts')
const NOTIFICATION_BELL_FILE = resolve(process.cwd(), 'app/components/notifications/NotificationBellButton.vue')
const NOTIFICATION_DRAWER_FILE = resolve(process.cwd(), 'app/components/notifications/NotificationDrawer.vue')
const NOTIFICATION_LIST_CONTENT_FILE = resolve(process.cwd(), 'app/components/notifications/NotificationListContent.vue')
const NOTIFICATION_COMPOSABLE_FILE = resolve(process.cwd(), 'app/composables/useNotificationCenter.ts')
const DASHBOARD_TOPBAR_FILE = resolve(process.cwd(), 'app/components/dashboard/DashboardTopbar.vue')
const WORKSPACE_HEADER_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceHeader.vue')
const WORKSPACE_LEFT_RAIL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceLeftRail.vue')
const WORKSPACE_LEFT_SIDEBAR_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceLeftSidebar.vue')
const WORKSPACE_NOTIFICATION_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceNotificationPanel.vue')
const ADMIN_INDEX_FILE = resolve(process.cwd(), 'app/pages/admin/index.vue')
const ADMIN_NOTIFICATIONS_PAGE_FILE = resolve(process.cwd(), 'app/pages/admin/notifications.vue')

it('通知领域类型与 user_notifications 表已落地', async () => {
  const domainSource = await readFile(DOMAIN_TYPES_FILE, 'utf8')
  const authTypesSource = await readFile(AUTH_TYPES_FILE, 'utf8')
  const schemaSource = await readFile(SCHEMA_FILE, 'utf8')

  assert.match(domainSource, /export \* from '\.\/auth'/, 'domain 类型聚合入口未转发 auth 模块')
  assert.match(authTypesSource, /UserNotificationCategory/, '通知分类类型缺失')
  assert.match(authTypesSource, /UserNotificationListResult/, '通知列表返回结构缺失')
  assert.match(schemaSource, /CREATE TABLE IF NOT EXISTS user_notifications \(/, 'user_notifications 表未创建')
  assert.match(schemaSource, /UNIQUE\(user_id, dedupe_key\)/, '通知去重约束缺失')
  assert.match(schemaSource, /idx_user_notifications_user_created/, '通知列表索引缺失')
})

it('通知 store 支持平台下发、比赛提醒与成员变更通知', async () => {
  const source = await readFile(NOTIFICATION_STORE_FILE, 'utf8')

  assert.match(source, /export async function ensureContestDeadlineNotifications\(/, '比赛提醒惰性生成入口缺失')
  assert.match(source, /contest\.deadline_reminder/, '比赛提醒通知类型未接入')
  assert.match(source, /export async function publishPlatformAnnouncement\(/, '平台通知发布函数缺失')
  assert.match(source, /export async function emitProjectMemberMutationNotifications\(/, '项目成员变更通知函数缺失')
  assert.match(source, /export async function emitWorkspaceMemberRemovedNotifications\(/, 'workspace 成员移除通知函数缺失')
})

it('通知 API 与业务写路径已接线', async () => {
  const listApiSource = await readFile(NOTIFICATION_LIST_API_FILE, 'utf8')
  const readAllApiSource = await readFile(NOTIFICATION_READ_ALL_API_FILE, 'utf8')
  const adminApiSource = await readFile(ADMIN_NOTIFICATION_API_FILE, 'utf8')
  const teamInviteApiSource = await readFile(TEAM_INVITE_API_FILE, 'utf8')
  const projectInviteApiSource = await readFile(PROJECT_INVITE_API_FILE, 'utf8')
  const acceptApiSource = await readFile(INVITE_ACCEPT_API_FILE, 'utf8')
  const platformStoreSource = await readFile(PLATFORM_STORE_FILE, 'utf8')
  const teamMembershipSource = await readFile(TEAM_MEMBERSHIP_STORE_FILE, 'utf8')

  assert.match(listApiSource, /ensureContestDeadlineNotifications/, '通知列表接口未接入比赛提醒惰性生成')
  assert.match(listApiSource, /listUserNotifications/, '通知列表接口未接入通知查询')
  assert.match(readAllApiSource, /markAllUserNotificationsRead/, '全部已读接口缺失')
  assert.match(adminApiSource, /publishPlatformAnnouncement/, '管理端通知发布接口缺失')
  assert.match(teamInviteApiSource, /emitInvitationCreatedNotifications/, 'Team 邀请创建未接入通知')
  assert.match(projectInviteApiSource, /emitInvitationCreatedNotifications/, '项目邀请创建未接入通知')
  assert.match(acceptApiSource, /emitInvitationAcceptedNotifications/, '邀请接受未接入通知')
  assert.match(platformStoreSource, /emitProjectMemberMutationNotifications/, '项目成员写路径未接入通知')
  assert.match(teamMembershipSource, /emitWorkspaceMemberRemovedNotifications/, 'workspace 成员移除未接入通知')
})

it('前端已接入共享通知中心与工作区左栏模块入口', async () => {
  const bellSource = await readFile(NOTIFICATION_BELL_FILE, 'utf8')
  const drawerSource = await readFile(NOTIFICATION_DRAWER_FILE, 'utf8')
  const listContentSource = await readFile(NOTIFICATION_LIST_CONTENT_FILE, 'utf8')
  const composableSource = await readFile(NOTIFICATION_COMPOSABLE_FILE, 'utf8')
  const dashboardTopbarSource = await readFile(DASHBOARD_TOPBAR_FILE, 'utf8')
  const workspaceHeaderSource = await readFile(WORKSPACE_HEADER_FILE, 'utf8')
  const workspaceLeftRailSource = await readFile(WORKSPACE_LEFT_RAIL_FILE, 'utf8')
  const workspaceLeftSidebarSource = await readFile(WORKSPACE_LEFT_SIDEBAR_FILE, 'utf8')
  const workspaceNotificationPanelSource = await readFile(WORKSPACE_NOTIFICATION_PANEL_FILE, 'utf8')
  const adminIndexSource = await readFile(ADMIN_INDEX_FILE, 'utf8')
  const adminNotificationsPageSource = await readFile(ADMIN_NOTIFICATIONS_PAGE_FILE, 'utf8')

  assert.match(composableSource, /export function useNotificationCenter\(\)/, '通知中心 composable 缺失')
  assert.match(composableSource, /\/notifications\/read-all/, '通知中心未接入全部已读接口')
  assert.match(composableSource, /POLL_INTERVAL_MS = 60_000/, '通知中心缺少轮询策略')
  assert.match(drawerSource, /title="通知中心"/, '通知抽屉标题缺失')
  assert.match(drawerSource, /import NotificationListContent from '~\/components\/notifications\/NotificationListContent\.vue'/, '通知抽屉未显式导入通知列表主体，嵌套组件解析在运行时会失效')
  assert.match(drawerSource, /v-model:visible="drawerVisible"/, '通知抽屉未通过共享状态受控打开')
  assert.match(drawerSource, /<NotificationListContent surface="drawer" \/>/, '通知抽屉未收敛成 drawer 壳层')
  assert.match(listContentSource, /surface\?: 'drawer' \| 'workspace'/, '通知列表主体未抽成复用 surface 组件')
  assert.match(listContentSource, /data-testid="workspace-left-panel-notification-module"/, '工作区通知列表缺少稳定测试锚点')
  assert.match(workspaceNotificationPanelSource, /<NotificationListContent surface="workspace" \/>/, '工作区通知模块未复用通知列表主体')
  assert.match(workspaceNotificationPanelSource, /import NotificationListContent from '~\/components\/notifications\/NotificationListContent\.vue'/, '工作区通知模块未显式导入通知列表主体，运行时会解析失败')
  assert.match(workspaceNotificationPanelSource, /void center\.refresh\(\)/, '工作区通知模块打开时未刷新通知列表')
  assert.match(workspaceNotificationPanelSource, /<UiButton/, '工作区通知模块未改用通用按钮组件承载全部已读')
  assert.match(workspaceNotificationPanelSource, /variant="secondary"/, '工作区通知模块全部已读按钮未使用通用次级按钮样式')
  assert.match(workspaceNotificationPanelSource, />\s*全部已读\s*<\/UiButton>/, '工作区通知模块全部已读按钮文案缺失')
  assert.match(workspaceNotificationPanelSource, /'暂无新消息'/, '工作区通知模块在零未读时未展示暂无新消息文案')
  assert.match(bellSource, /variant\?: 'default' \| 'rail'/, '通知铃铛未支持 rail 变体')
  assert.match(bellSource, /active\?: boolean/, '通知铃铛缺少 rail 场景显式激活态入参')
  assert.match(bellSource, /const \{ drawerVisible, initialized, unreadCount \} = center/, '通知铃铛未复用共享抽屉打开态')
  assert.match(bellSource, /const isRailActive = computed\(\(\) => isRailVariant\.value \? props\.active : drawerVisible\.value\)/, '通知铃铛未区分 rail 与 drawer 的激活态来源')
  assert.match(bellSource, /if \(isRailVariant\.value\) \{[\s\S]*emit\('open'\)[\s\S]*return/, 'rail 通知铃铛未改成只上抛打开事件')
  assert.match(bellSource, /if \(drawerVisible\.value\) \{[\s\S]*center\.closeDrawer\(\)/, '默认通知铃铛再次点击时未切换为关闭')
  assert.match(bellSource, /pointer-events: auto;/, '左 rail 通知标签仍不可点击')
  assert.match(bellSource, /<NotificationDrawer v-if="!isRailVariant" :workspace-id="props\.workspaceId" \/>/, '工作区 rail 铃铛仍挂载通知抽屉')
  assert.match(dashboardTopbarSource, /import NotificationBellButton from '~\/components\/notifications\/NotificationBellButton\.vue'/, 'Dashboard 顶栏未显式导入通知铃铛')
  assert.match(dashboardTopbarSource, /<NotificationBellButton :workspace-id="workspaceId" \/>/, 'Dashboard 顶栏未接入通知铃铛')
  assert.doesNotMatch(workspaceHeaderSource, /NotificationBellButton/, 'Workspace 头部仍保留旧的通知铃铛入口')
  assert.match(workspaceLeftRailSource, /<NotificationBellButton[\s\S]*variant="rail"/, 'Workspace 左 rail 未接入通知铃铛')
  assert.match(workspaceLeftRailSource, /data-testid="workspace-left-rail-notification-button"/, 'Workspace 左 rail 缺少通知入口测试标记')
  assert.match(workspaceLeftRailSource, /notificationActive\?: boolean/, 'Workspace 左 rail 未暴露通知激活态入参')
  assert.match(workspaceLeftRailSource, /:active="props\.notificationActive"/, 'Workspace 左 rail 未向通知铃铛透传激活态')
  assert.match(workspaceLeftSidebarSource, /switchModule\('notification_center'\)/, 'Workspace 左栏未将通知入口改成左侧模块切换')
  assert.match(workspaceLeftSidebarSource, /<WorkspaceNotificationPanel[\s\S]*:workspace-id="props\.workspaceId"/, 'Workspace 左栏未挂载通知中心模块')
  assert.match(adminIndexSource, /to="\/admin\/notifications"/, '管理首页缺少通知管理入口')
  assert.match(adminNotificationsPageSource, /通知管理/, '后台独立通知管理页缺失')
  assert.match(adminNotificationsPageSource, /Publish Notification/, '独立通知管理页缺少发布表单')
  assert.match(adminNotificationsPageSource, /\/admin\/notifications/, '独立通知管理页未接入通知发布接口')
})
