import assert from 'node:assert/strict'
import { readdir, readFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { it } from 'vitest'

const DOMAIN_BARREL_FILE = resolve(process.cwd(), 'shared/types/domain.ts')
const DOMAIN_LEGACY_FILE = resolve(process.cwd(), 'shared/types/domain-legacy.ts')
const MAIN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanel.vue')
const MAIN_PANEL_CHROME_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanelChrome.vue')
const DESIGN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceDesignPanel.vue')
const DESIGN_CANVASKIT_BRIDGE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignCanvasKitBridge.client.vue')
const DESIGN_CANVASKIT_HOST_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignCanvasKitHost.client.vue')
const DESIGN_CANVAS_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignCanvas.client.vue')
const DESIGN_DIAGRAM_EDITOR_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramEditor.client.vue')
const DESIGN_DIAGRAM_GROUP_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramGroupNode.vue')
const DESIGN_DIAGRAM_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramNode.vue')
const DESIGN_FRAME_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignFrameNode.vue')
const LEGACY_DESIGN_FLOATING_TOOLBAR_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignFloatingToolbar.vue')
const LEGACY_DESIGN_SIDEBAR_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignSidebarPanel.vue')
const LEGACY_DESIGN_SHELL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignShell.vue')
const LEGACY_DESIGN_LAYERS_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignLayersPanel.vue')
const FLOW_TAB_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceFlowTab.vue')
const TLDRAW_FILE = resolve(process.cwd(), 'app/components/workspace/collab/WorkspaceTldrawCanvas.client.vue')
const SCENE_PREVIEW_FILE = resolve(process.cwd(), 'app/components/workspace/collab/WorkspaceScenePreview.vue')
const ORCHESTRATOR_FILE = resolve(process.cwd(), 'server/services/ai/workspace-orchestrator.ts')
const COLLAB_POST_FILE = resolve(process.cwd(), 'server/api/projects/[id]/resources/collab.post.ts')
const VIEW_STORE_FILE = resolve(process.cwd(), 'server/utils/project-workspace-view-store.ts')
const WORKSPACE_COMPONENTS_DIR = resolve(process.cwd(), 'app/components/workspace')

async function readWorkspaceComponentSources(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const chunks = await Promise.all(entries.map(async (entry) => {
    const absolutePath = join(dir, entry.name)
    if (entry.isDirectory())
      return readWorkspaceComponentSources(absolutePath)
    if (!entry.isFile() || !absolutePath.endsWith('.vue'))
      return ''
    return readFile(absolutePath, 'utf8')
  }))

  return chunks.join('\n')
}

it('统一 scene 平台基础骨架已接入共享类型与设计画布资源页签', async () => {
  const domainBarrelSource = await readFile(DOMAIN_BARREL_FILE, 'utf8')
  const domainLegacySource = await readFile(DOMAIN_LEGACY_FILE, 'utf8')
  const mainPanelSource = await readFile(MAIN_PANEL_FILE, 'utf8')
  const chromeSource = await readFile(MAIN_PANEL_CHROME_FILE, 'utf8')
  const designPanelSource = await readFile(DESIGN_PANEL_FILE, 'utf8')
  const designCanvasKitBridgeSource = await readFile(DESIGN_CANVASKIT_BRIDGE_FILE, 'utf8')
  const designCanvasKitHostSource = await readFile(DESIGN_CANVASKIT_HOST_FILE, 'utf8')
  const designCanvasSource = await readFile(DESIGN_CANVAS_FILE, 'utf8')
  const designDiagramEditorSource = await readFile(DESIGN_DIAGRAM_EDITOR_FILE, 'utf8')
  const designDiagramGroupNodeSource = await readFile(DESIGN_DIAGRAM_GROUP_NODE_FILE, 'utf8')
  const designDiagramNodeSource = await readFile(DESIGN_DIAGRAM_NODE_FILE, 'utf8')
  const designFrameNodeSource = await readFile(DESIGN_FRAME_NODE_FILE, 'utf8')
  const flowTabSource = await readFile(FLOW_TAB_FILE, 'utf8')
  const viewStoreSource = await readFile(VIEW_STORE_FILE, 'utf8')
  const workspaceComponentSources = await readWorkspaceComponentSources(WORKSPACE_COMPONENTS_DIR)

  assert.match(domainBarrelSource, /export \* from '\.\/resource'/)
  assert.match(domainBarrelSource, /export \* from '\.\/workspace'/)
  assert.match(domainLegacySource, /export type DrawMode = 'freeform' \| 'diagram' \| 'schema' \| 'architecture' \| 'composition'/)
  assert.match(domainLegacySource, /export interface SceneDocument \{/)
  assert.match(domainLegacySource, /export interface SchemaModel \{/)
  assert.match(domainLegacySource, /export interface ArchitectureModel \{/)
  assert.match(domainLegacySource, /export interface CompositionModel \{/)
  assert.match(domainLegacySource, /export type SceneEditorEngine = 'vueflow' \| 'tldraw_legacy' \| 'canvaskit_wasm'/)
  assert.match(domainLegacySource, /export interface DesignPageModel \{/)
  assert.match(domainLegacySource, /export interface DesignFrameModel \{/)
  assert.match(domainLegacySource, /export type WorkspaceFixedTabId = 'dashboard' \| 'meeting' \| 'members' \| 'flow' \| 'settings'/)

  assert.match(mainPanelSource, /<WorkspaceDesignPanel/)
  assert.match(mainPanelSource, /isActiveDesignResource/)
  assert.match(mainPanelSource, /activeDesignPanelTitle/)
  assert.match(mainPanelSource, /migrateLegacyOpenTabsFromProps/)
  assert.match(mainPanelSource, /:design-editor-engine="activeResource\?\.editorEngine \|\| ''"/)
  assert.doesNotMatch(mainPanelSource, /openDesignSignal/)
  assert.doesNotMatch(mainPanelSource, /id: 'design'/)
  assert.doesNotMatch(chromeSource, /openDesign/)
  assert.doesNotMatch(chromeSource, /打开设计/)

  assert.match(designPanelSource, /buildDeviceMockupSceneDocument/)
  assert.match(designPanelSource, /renderCompositionAssetToSvg/)
  assert.match(designPanelSource, /appendDesignPageToSceneDocument/)
  assert.match(designPanelSource, /appendDesignFrameToSceneDocument/)
  assert.match(designPanelSource, /WorkspaceDesignCanvas/)
  assert.match(designPanelSource, /WLDesignLayout/)
  assert.match(designPanelSource, /WLDesignContainer/)
  assert.match(designPanelSource, /WLDesignLayer/)
  assert.match(designPanelSource, /Frames/)
  assert.match(designPanelSource, /Diagram 编辑态/)
  assert.match(designPanelSource, /openFrameEditor/)
  assert.match(designPanelSource, /diagramEditorGraph/)
  assert.match(designPanelSource, /Graph Controls/)
  assert.match(designPanelSource, /Diagram Canvas/)
  assert.match(designPanelSource, /Selection Inspector/)
  assert.match(designPanelSource, /:selected-group-id=/)
  assert.match(designPanelSource, /Selected Group/)
  assert.match(designPanelSource, /lane direction/)
  assert.match(designPanelSource, /整理成员/)
  assert.match(designPanelSource, /按内容收紧/)
  assert.match(designPanelSource, /恢复自动布局/)
  assert.match(designPanelSource, /Selected Node/)
  assert.match(designPanelSource, /Selected Edge/)
  assert.match(designPanelSource, /Nodes/)
  assert.match(designPanelSource, /Edges/)
  assert.match(designPanelSource, /toggleDiagramGraphGroupMembership/)
  assert.match(designPanelSource, /addDiagramGraphNode/)
  assert.match(designPanelSource, /addDiagramGraphGroup/)
  assert.match(designPanelSource, /diagramSelectedGroupSceneNode/)
  assert.match(designPanelSource, /updateDiagramGraphGroupFrame/)
  assert.match(designPanelSource, /relayoutDiagramGraphGroup/)
  assert.match(designPanelSource, /fitDiagramGraphGroupToMembers/)
  assert.match(designPanelSource, /resetDiagramGraphGroupManualLayout/)
  assert.match(designPanelSource, /laneDirection/)
  assert.match(designPanelSource, /addDiagramChildNode/)
  assert.match(designPanelSource, /addDiagramGraphEdge/)
  assert.match(designPanelSource, /duplicateDiagramGraphNode/)
  assert.match(designPanelSource, /updateDiagramGraphGroup/)
  assert.match(designPanelSource, /removeDiagramGraphGroup/)
  assert.match(designPanelSource, /reverseDiagramGraphEdge/)
  assert.match(designPanelSource, /connectDiagramGraphEdge/)
  assert.match(designPanelSource, /updateDiagramGraphNodePosition/)
  assert.match(designPanelSource, /update:modelValue/)
  assert.match(designPanelSource, /parseSceneDocumentString/)
  assert.match(designPanelSource, /isBoundToDesignResource/)
  assert.match(designPanelSource, /WorkspaceDesignCanvasKitBridge/)
  assert.match(designPanelSource, /resolvedDesignStageComponent/)
  assert.match(designPanelSource, /persistedDesignEditorEngine\.value === "tldraw_legacy"/)
  assert.match(designPanelSource, /:is="resolvedDesignStageComponent"/)
  assert.match(designPanelSource, /@duplicate-element="duplicateSelectedElement"/)
  assert.match(designPanelSource, /@delete-element="removeSelectedElement"/)
  assert.match(designPanelSource, /designToolController\.isDrawingTool\.value[\s\S]*setActiveDesignTool\("select"\)/)
  assert.match(designPanelSource, /导出 Page PNG/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignFloatingToolbar/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignSidebarPanel/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignShell/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignLayersPanel/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignFloatingToolbar/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignSidebarPanel/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignShell/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignLayersPanel/)
  assert.match(designCanvasSource, /@node-drag-start=/)
  assert.match(designCanvasSource, /@node-drag=/)
  assert.match(designCanvasSource, /@node-double-click/)
  assert.match(designCanvasSource, /dragFeedback/)
  assert.match(designCanvasSource, /handleKeydown/)
  assert.match(designCanvasSource, /Arrow/)
  assert.match(designCanvasSource, /tabindex="0"/)
  assert.match(designCanvasSource, /X 对齐/)
  assert.match(designCanvasSource, /duplicate-frame/)
  assert.match(designCanvasSource, /delete-frame/)
  assert.match(designCanvasSource, /update-frame-size/)
  assert.match(designCanvasSource, /onResizePreview/)
  assert.match(designCanvasSource, /onResizeCommit/)
  assert.match(designCanvasSource, /open-frame/)
  assert.match(designCanvasSource, /pan-on-scroll/)
  assert.match(designCanvasSource, /zoom-on-pinch/)
  assert.match(designDiagramEditorSource, /WorkspaceDesignDiagramNode/)
  assert.match(designDiagramEditorSource, /WorkspaceDesignDiagramGroupNode/)
  assert.match(designDiagramEditorSource, /@connect=/)
  assert.match(designDiagramEditorSource, /@node-double-click=/)
  assert.match(designDiagramEditorSource, /@node-drag-start=/)
  assert.match(designDiagramEditorSource, /@node-drag=/)
  assert.match(designDiagramEditorSource, /@node-drag-stop=/)
  assert.match(designDiagramEditorSource, /dragFeedback/)
  assert.match(designDiagramEditorSource, /update-node-position/)
  assert.match(designDiagramEditorSource, /update-group-frame/)
  assert.match(designDiagramEditorSource, /onResizeGroup/)
  assert.match(designDiagramEditorSource, /select-group/)
  assert.match(designDiagramEditorSource, /selectedGroupId/)
  assert.match(designDiagramEditorSource, /create-group/)
  assert.match(designDiagramEditorSource, /delete-group/)
  assert.match(designDiagramEditorSource, /New Group/)
  assert.match(designDiagramEditorSource, /New Lane/)
  assert.match(designDiagramEditorSource, /Add Child/)
  assert.match(designDiagramEditorSource, /Duplicate/)
  assert.match(designDiagramEditorSource, /Reverse/)
  assert.match(designDiagramEditorSource, /X 对齐/)
  assert.match(designDiagramEditorSource, /handleKeydown/)
  assert.match(designDiagramEditorSource, /emitNudgeSelection/)
  assert.match(designDiagramEditorSource, /arrowleft/)
  assert.match(designDiagramEditorSource, /Cmd\/Ctrl \+ D/)
  assert.match(designDiagramEditorSource, /tabindex="0"/)
  assert.match(designDiagramEditorSource, /select-node/)
  assert.match(designDiagramGroupNodeSource, /layoutKind/)
  assert.match(designDiagramGroupNodeSource, /startResize/)
  assert.match(designDiagramGroupNodeSource, /onResizeGroup/)
  assert.match(designDiagramGroupNodeSource, /cursor-se-resize/)
  assert.match(designDiagramGroupNodeSource, /@pointerdown.stop.prevent/)
  assert.match(designDiagramGroupNodeSource, /Untitled Group/)
  assert.match(designDiagramNodeSource, /Handle/)
  assert.match(designDiagramNodeSource, /Position.Left/)
  assert.match(designDiagramNodeSource, /cursor-pointer/)
  assert.match(designCanvasKitBridgeSource, /data-testid="workspace-design-canvaskit-bridge"/)
  assert.match(designCanvasKitBridgeSource, /CanvasKit/)
  assert.match(designCanvasKitBridgeSource, /WorkspaceDesignCanvasKitHost/)
  assert.match(designCanvasKitBridgeSource, /pending-image-placement/)
  assert.match(designCanvasKitBridgeSource, /clear-pending-image-placement/)
  assert.match(designCanvasKitBridgeSource, /@duplicate-element="emit\('duplicate-element'\)"/)
  assert.match(designCanvasKitBridgeSource, /@delete-element="emit\('delete-element'\)"/)
  assert.doesNotMatch(designCanvasKitBridgeSource, /WorkspaceDesignStage/)
  assert.match(designCanvasKitHostSource, /data-testid="workspace-design-canvaskit-host"/)
  assert.match(designCanvasKitHostSource, /renderCompositionAssetToSvg/)
  assert.match(designCanvasKitHostSource, /canDesignFrameCreateElements/)
  assert.match(designCanvasKitHostSource, /emit\('viewport-change',/)
  assert.match(designCanvasKitHostSource, /emit\('update-selection',/)
  assert.match(designCanvasKitHostSource, /emit\('open-frame',/)
  assert.match(designCanvasKitHostSource, /emit\('request-deep-selection',/)
  assert.match(designCanvasKitHostSource, /data-testid="workspace-design-canvaskit-minimap"/)
  assert.match(designCanvasKitHostSource, /data-testid="workspace-design-canvaskit-zoom-hud"/)
  assert.match(designCanvasKitHostSource, /zoomControlState/)
  assert.match(designCanvasKitHostSource, /zoomCollapsedIndicatorStyle/)
  assert.match(designCanvasKitHostSource, /handleMinimapPointerDown/)
  assert.match(designCanvasKitHostSource, /handleZoomControlPointerEnter/)
  assert.match(designCanvasKitHostSource, /handleElementPointerDown/)
  assert.match(designCanvasKitHostSource, /element-drag:/)
  assert.match(designCanvasKitHostSource, /handleElementResizePointerDown/)
  assert.match(designCanvasKitHostSource, /element-resize:/)
  assert.match(designCanvasKitHostSource, /type CreateElementSession = \{/)
  assert.match(designCanvasKitHostSource, /type TextEditSession = \{/)
  assert.match(designCanvasKitHostSource, /type SelectionDraft = \{/)
  assert.match(designCanvasKitHostSource, /type ElementRotationSession = \{/)
  assert.match(designCanvasKitHostSource, /type MockupScreenDragSession = \{/)
  assert.match(designCanvasKitHostSource, /type PendingImagePlacement = \{/)
  assert.match(designCanvasKitHostSource, /type GroupEditSession = \{/)
  assert.match(designCanvasKitHostSource, /type ElementGuideOverlay = \{/)
  assert.match(designCanvasKitHostSource, /type AutoLayoutReorderSession = \{/)
  assert.match(designCanvasKitHostSource, /type FrameDragSession = \{/)
  assert.match(designCanvasKitHostSource, /type FrameResizeSession = \{/)
  assert.match(designCanvasKitHostSource, /type FrameDragFeedback = \{/)
  assert.match(designCanvasKitHostSource, /const activeCreateElementTool = computed/)
  assert.match(designCanvasKitHostSource, /const createElementEnabled = computed/)
  assert.match(designCanvasKitHostSource, /const pendingImagePlacementState = computed/)
  assert.match(designCanvasKitHostSource, /const selectionDraftRectStyle = computed/)
  assert.match(designCanvasKitHostSource, /const textEditStyle = computed/)
  assert.match(designCanvasKitHostSource, /const elementTransformBoxStyle = computed/)
  assert.match(designCanvasKitHostSource, /const activeMockupScreenEditingLayout = computed/)
  assert.match(designCanvasKitHostSource, /const visibleFrameGrids = computed/)
  assert.match(designCanvasKitHostSource, /&& !createElementEnabled\.value/)
  assert.match(designCanvasKitHostSource, /function emitCreateElementFromSession/)
  assert.match(designCanvasKitHostSource, /function resolveCreateSessionFrameContextForFrame/)
  assert.match(designCanvasKitHostSource, /function emitFrameEditingSelection/)
  assert.match(designCanvasKitHostSource, /function emitFrameSelection/)
  assert.match(designCanvasKitHostSource, /function beginCreateElementSession/)
  assert.match(designCanvasKitHostSource, /function handleFramePointerDown/)
  assert.match(designCanvasKitHostSource, /function openTextEditSession/)
  assert.match(designCanvasKitHostSource, /function closeTextEditSession/)
  assert.match(designCanvasKitHostSource, /function resolveSelectionDraftMatches/)
  assert.match(designCanvasKitHostSource, /function beginGroupEditSession/)
  assert.match(designCanvasKitHostSource, /function resolveElementGuideAdjustment/)
  assert.match(designCanvasKitHostSource, /function beginAutoLayoutReorderSession/)
  assert.match(designCanvasKitHostSource, /function handleElementRotatePointerDown/)
  assert.match(designCanvasKitHostSource, /function handleElementDoubleClick/)
  assert.match(designCanvasKitHostSource, /function resolveMockupScreenTransform/)
  assert.match(designCanvasKitHostSource, /function resolveFrameDragAssist/)
  assert.match(designCanvasKitHostSource, /function setFrameDragFeedback/)
  assert.match(designCanvasKitHostSource, /function clearFrameDragFeedback/)
  assert.match(designCanvasKitHostSource, /function handleFrameResizePointerDown/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-create-preview/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-create-arrow-preview/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-create-path-preview/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-selection-preview/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-text-editor/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-element-rotate/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-mockup-screen/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-element-guide-overlay/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-autolayout-indicator/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-frame-resize/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-frame-feedback/)
  assert.match(designCanvasKitHostSource, /workspace-design-canvaskit-frame-guides/)
  assert.match(designCanvasKitHostSource, /props\.activeTool === 'pencil'/)
  assert.match(designCanvasKitHostSource, /type: 'path'/)
  assert.match(designCanvasKitHostSource, /tool === 'image'/)
  assert.match(designCanvasKitHostSource, /pendingCreatedTextEdit\.value = \{/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'element-text-edit'/)
  assert.match(designCanvasKitHostSource, /element-rotate:/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'element-reorder'/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'mockup-screen-transform'/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'frame-resize'/)
  assert.match(designCanvasKitHostSource, /ELEMENT_SNAP_GRID_SIZE = 8/)
  assert.match(designCanvasKitHostSource, /ELEMENT_SNAP_THRESHOLD = 8/)
  assert.match(designCanvasKitHostSource, /resolveDesignFrameGridMetadata/)
  assert.match(designCanvasKitHostSource, /columnGuides/)
  assert.match(designCanvasKitHostSource, /rowGuides/)
  assert.match(designCanvasKitHostSource, /shapeKind: session\.tool === 'ellipse' \? 'ellipse' : session\.tool === 'arrow' \? 'arrow' : 'rectangle'/)
  assert.match(designCanvasKitHostSource, /data-testid="workspace-design-canvaskit-element-resize"/)
  assert.match(designCanvasKitHostSource, /@pointerdown\.stop="handleFramePointerDown\(frame, \$event\)"/)
  assert.match(designCanvasKitHostSource, /scope: 'none',\s*editingFrameId: context\.ownerFrameId,\s*displayFrameId: context\.displayFrameId/)
  assert.match(designCanvasKitHostSource, /const cursor = activeCreateElementTool\.value \|\| pendingImagePlacementState\.value\s*\?\s*'crosshair'/)
  assert.match(designCanvasKitHostSource, /function handleKeydown/)
  assert.match(designCanvasKitHostSource, /if \(activeCreateElementTool\.value \|\| pendingImagePlacementState\.value \|\| textEditSession\.value\)\s*return/)
  assert.match(designCanvasKitHostSource, /tabindex="0"/)
  assert.match(designCanvasKitHostSource, /emit\('duplicate-element'\)/)
  assert.match(designCanvasKitHostSource, /emit\('delete-element'\)/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'element-nudge'/)
  assert.match(designCanvasKitHostSource, /historyMergeKey: 'frame-nudge'/)
  assert.match(designCanvasKitHostSource, /function fitCanvasView/)
  assert.match(designCanvasKitHostSource, /zoomDisplayText/)
  assert.match(designCanvasKitHostSource, /data-testid="workspace-design-canvaskit-element-hit"/)
  assert.match(designPanelSource, /const pendingImagePlacement = ref<PendingImagePlacement \| null>\(null\)/)
  assert.match(designPanelSource, /@insert-image-file="void handleToolbarInsertImage\(\$event\)"/)
  assert.match(designPanelSource, /@clear-pending-image-placement="clearPendingImagePlacement"/)
  assert.match(designPanelSource, /groupDesignElementsInSceneDocument/)
  assert.match(designPanelSource, /ungroupDesignElementInSceneDocument/)
  assert.match(designPanelSource, /"group"/)
  assert.match(designPanelSource, /"ungroup"/)
  assert.match(designPanelSource, /"bring-forward"/)
  assert.match(designPanelSource, /"send-backward"/)
  assert.match(designPanelSource, /"bring-to-front"/)
  assert.match(designPanelSource, /"send-to-back"/)
  assert.match(workspaceComponentSources, /workspace-design-toolbar-image-action/)
  assert.match(designFrameNodeSource, /frame.kind === 'diagram'/)
  assert.match(designFrameNodeSource, /isDeviceDesignFrameKind/)
  assert.match(designFrameNodeSource, /renderCompositionFramePreviewSvg/)
  assert.doesNotMatch(designFrameNodeSource, /\bpreviewFrame\b/)
  assert.match(designFrameNodeSource, /:\s*\[props\.frame\]/)
  assert.match(designFrameNodeSource, /frames:\s*previewFrames,/)
  assert.match(designFrameNodeSource, /deviceFramePreviewSvg/)
  assert.match(designFrameNodeSource, /startResize/)
  assert.match(designFrameNodeSource, /cursor-se-resize/)
  assert.match(designFrameNodeSource, /onResizePreview/)
  assert.match(designFrameNodeSource, /onResizeCommit/)
  assert.match(designPanelSource, /useDesignHistory/)
  assert.match(designPanelSource, /useDesignCanvasSelection/)
  assert.match(designCanvasSource, /device_artboard/)

  assert.match(flowTabSource, /importFromMermaid|WorkspaceDrawioCanvas/)
  assert.match(flowTabSource, /importFromMarkdownOutline|draw\.io/)
  assert.match(flowTabSource, /importFromDDL|AgentProto/)
  assert.match(flowTabSource, /importArchitectureFromMetadata|collabDrawValue/)
  assert.match(flowTabSource, /结构源导入|流程画布/)
  assert.match(flowTabSource, /pointer-events-none absolute right-3 top-3 z-10 items-center|WorkspaceDrawioCanvas/)
  assert.match(flowTabSource, /docker-compose|flow-canvas/)
  assert.match(flowTabSource, /workspace manifests|实时连接中/)
  assert.match(flowTabSource, /OpenAPI|暂未初始化流程画布/)

  assert.match(viewStoreSource, /'dashboard', 'meeting', 'members', 'flow', 'settings'/)
  assert.match(viewStoreSource, /preserveLegacyDesignTab: true/)

  await assert.rejects(readFile(LEGACY_DESIGN_FLOATING_TOOLBAR_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_SIDEBAR_PANEL_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_SHELL_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_LAYERS_PANEL_FILE, 'utf8'))
})

it('画布兼容层保留 SceneDocument 能力，工作台 orchestrator 不再暴露 scene 工具', async () => {
  const tldrawSource = await readFile(TLDRAW_FILE, 'utf8')
  const previewSource = await readFile(SCENE_PREVIEW_FILE, 'utf8')
  const orchestratorSource = await readFile(ORCHESTRATOR_FILE, 'utf8')
  const collabPostSource = await readFile(COLLAB_POST_FILE, 'utf8')

  assert.match(tldrawSource, /WorkspaceScenePreview/)
  assert.match(tldrawSource, /sceneDocumentHasStructuredPreview/)
  assert.match(tldrawSource, /withRuntimeSnapshot/)
  assert.match(tldrawSource, /serializeSceneDocument/)
  assert.match(tldrawSource, /scenePreviewDocument/)
  assert.match(tldrawSource, /useRuntimeConfig\(\)/)
  assert.match(tldrawSource, /licenseKey: tldrawLicenseKey\.value \|\| undefined/)
  assert.match(tldrawSource, /WINLOOP_TLDRAW_LICENSE_KEY/)

  assert.match(previewSource, /renderCompositionAssetToSvg/)
  assert.match(previewSource, /sceneDocumentFromUnknown/)

  assert.doesNotMatch(orchestratorSource, /name: 'generate_scene_from_text'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_schema_from_ddl'/)
  assert.doesNotMatch(orchestratorSource, /name: 'export_schema_to_ddl'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_architecture_from_metadata'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_architecture_from_repo'/)
  assert.doesNotMatch(orchestratorSource, /scanRepoArchitecture/)
  assert.doesNotMatch(orchestratorSource, /name: 'export_architecture_to_mermaid'/)
  assert.doesNotMatch(orchestratorSource, /name: 'apply_template'/)
  assert.doesNotMatch(orchestratorSource, /name: 'relayout_scene'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_device_mockup'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_design_page'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_design_frame'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_diagram_frame'/)
  assert.doesNotMatch(orchestratorSource, /name: 'generate_device_mockup_frame'/)
  assert.doesNotMatch(orchestratorSource, /name: 'export_design_asset'/)
  assert.doesNotMatch(orchestratorSource, /name: 'export_scene_asset'/)

  assert.match(collabPostSource, /drawMode\?: string/)
  assert.match(collabPostSource, /sceneSourceType\?: string/)
  assert.match(collabPostSource, /templateKey\?: string/)
  assert.match(collabPostSource, /editorEngine\?: string/)
  assert.match(collabPostSource, /purpose 仅支持 workflow \/ freeform \/ design \/ notes/)
  assert.doesNotMatch(collabPostSource, /ensureProjectDesignCanvas/)
  assert.match(collabPostSource, /purpose === 'design'[\s\S]*drawMode: normalizeString\(body\.drawMode \|\| requestMetadata\.drawMode\) \|\| 'composition'/)
  assert.match(collabPostSource, /metadata:\s*\{/)
})
