import assert from 'node:assert/strict'
import { readFile, readdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { it } from 'vitest'

const DOMAIN_BARREL_FILE = resolve(process.cwd(), 'shared/types/domain.ts')
const DOMAIN_LEGACY_FILE = resolve(process.cwd(), 'shared/types/domain-legacy.ts')
const MAIN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanel.vue')
const MAIN_PANEL_CHROME_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceMainPanelChrome.vue')
const DESIGN_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceDesignPanel.vue')
const DESIGN_CANVAS_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignCanvas.client.vue')
const DESIGN_DIAGRAM_EDITOR_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramEditor.client.vue')
const DESIGN_DIAGRAM_GROUP_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramGroupNode.vue')
const DESIGN_DIAGRAM_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignDiagramNode.vue')
const DESIGN_FRAME_NODE_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignFrameNode.vue')
const LEGACY_DESIGN_FLOATING_TOOLBAR_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignFloatingToolbar.vue')
const LEGACY_DESIGN_SIDEBAR_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignSidebarPanel.vue')
const LEGACY_DESIGN_SHELL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignShell.vue')
const LEGACY_DESIGN_LAYERS_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/design/WorkspaceDesignLayersPanel.vue')
const FLOW_TAB_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceFlowTab.vue')
const TLDRAW_FILE = resolve(process.cwd(), 'app/components/workspace/collab/WorkspaceTldrawCanvas.client.vue')
const SCENE_PREVIEW_FILE = resolve(process.cwd(), 'app/components/workspace/collab/WorkspaceScenePreview.vue')
const ORCHESTRATOR_FILE = resolve(process.cwd(), 'server/services/ai/workspace-orchestrator.ts')
const COLLAB_POST_FILE = resolve(process.cwd(), 'server/api/projects/[id]/resources/collab.post.ts')
const VIEW_STORE_FILE = resolve(process.cwd(), 'server/utils/project-workspace-view-store.ts')
const WORKSPACE_COMPONENTS_DIR = resolve(process.cwd(), 'app/components/workspace')

async function readWorkspaceComponentSources(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const chunks = await Promise.all(entries.map(async (entry) => {
    const absolutePath = join(dir, entry.name)
    if (entry.isDirectory())
      return readWorkspaceComponentSources(absolutePath)
    if (!entry.isFile() || !absolutePath.endsWith('.vue'))
      return ''
    return readFile(absolutePath, 'utf8')
  }))

  return chunks.join('\n')
}

it('统一 scene 平台基础骨架已接入共享类型与设计画布资源页签', async () => {
  const domainBarrelSource = await readFile(DOMAIN_BARREL_FILE, 'utf8')
  const domainLegacySource = await readFile(DOMAIN_LEGACY_FILE, 'utf8')
  const mainPanelSource = await readFile(MAIN_PANEL_FILE, 'utf8')
  const chromeSource = await readFile(MAIN_PANEL_CHROME_FILE, 'utf8')
  const designPanelSource = await readFile(DESIGN_PANEL_FILE, 'utf8')
  const designCanvasSource = await readFile(DESIGN_CANVAS_FILE, 'utf8')
  const designDiagramEditorSource = await readFile(DESIGN_DIAGRAM_EDITOR_FILE, 'utf8')
  const designDiagramGroupNodeSource = await readFile(DESIGN_DIAGRAM_GROUP_NODE_FILE, 'utf8')
  const designDiagramNodeSource = await readFile(DESIGN_DIAGRAM_NODE_FILE, 'utf8')
  const designFrameNodeSource = await readFile(DESIGN_FRAME_NODE_FILE, 'utf8')
  const flowTabSource = await readFile(FLOW_TAB_FILE, 'utf8')
  const viewStoreSource = await readFile(VIEW_STORE_FILE, 'utf8')
  const workspaceComponentSources = await readWorkspaceComponentSources(WORKSPACE_COMPONENTS_DIR)

  assert.match(domainBarrelSource, /export \* from '\.\/resource'/)
  assert.match(domainBarrelSource, /export \* from '\.\/workspace'/)
  assert.match(domainLegacySource, /export type DrawMode = 'freeform' \| 'diagram' \| 'schema' \| 'architecture' \| 'composition'/)
  assert.match(domainLegacySource, /export interface SceneDocument \{/)
  assert.match(domainLegacySource, /export interface SchemaModel \{/)
  assert.match(domainLegacySource, /export interface ArchitectureModel \{/)
  assert.match(domainLegacySource, /export interface CompositionModel \{/)
  assert.match(domainLegacySource, /export type SceneEditorEngine = 'vueflow' \| 'tldraw_legacy'/)
  assert.match(domainLegacySource, /export interface DesignPageModel \{/)
  assert.match(domainLegacySource, /export interface DesignFrameModel \{/)
  assert.match(domainLegacySource, /export type WorkspaceFixedTabId = 'dashboard' \| 'meeting' \| 'members' \| 'flow' \| 'design' \| 'settings'/)

  assert.match(mainPanelSource, /<WorkspaceDesignPanel/)
  assert.match(mainPanelSource, /openDesignSignal/)
  assert.match(mainPanelSource, /designPanelTitle/)
  assert.match(mainPanelSource, /migrateLegacyOpenTabsFromProps/)
  assert.match(mainPanelSource, /id: 'design'/)
  assert.doesNotMatch(chromeSource, /openDesign/)
  assert.doesNotMatch(chromeSource, /打开设计/)

  assert.match(designPanelSource, /buildDeviceMockupSceneDocument/)
  assert.match(designPanelSource, /renderCompositionAssetToSvg/)
  assert.match(designPanelSource, /appendDesignPageToSceneDocument/)
  assert.match(designPanelSource, /appendDesignFrameToSceneDocument/)
  assert.match(designPanelSource, /WorkspaceDesignCanvas/)
  assert.match(designPanelSource, /WLDesignLayout/)
  assert.match(designPanelSource, /WLDesignContainer/)
  assert.match(designPanelSource, /WLDesignLayer/)
  assert.match(designPanelSource, /Frames/)
  assert.match(designPanelSource, /Diagram 编辑态/)
  assert.match(designPanelSource, /openFrameEditor/)
  assert.match(designPanelSource, /diagramEditorGraph/)
  assert.match(designPanelSource, /Graph Controls/)
  assert.match(designPanelSource, /Diagram Canvas/)
  assert.match(designPanelSource, /Selection Inspector/)
  assert.match(designPanelSource, /:selected-group-id=/)
  assert.match(designPanelSource, /Selected Group/)
  assert.match(designPanelSource, /lane direction/)
  assert.match(designPanelSource, /整理成员/)
  assert.match(designPanelSource, /按内容收紧/)
  assert.match(designPanelSource, /恢复自动布局/)
  assert.match(designPanelSource, /Selected Node/)
  assert.match(designPanelSource, /Selected Edge/)
  assert.match(designPanelSource, /Nodes/)
  assert.match(designPanelSource, /Edges/)
  assert.match(designPanelSource, /toggleDiagramGraphGroupMembership/)
  assert.match(designPanelSource, /addDiagramGraphNode/)
  assert.match(designPanelSource, /addDiagramGraphGroup/)
  assert.match(designPanelSource, /diagramSelectedGroupSceneNode/)
  assert.match(designPanelSource, /updateDiagramGraphGroupFrame/)
  assert.match(designPanelSource, /relayoutDiagramGraphGroup/)
  assert.match(designPanelSource, /fitDiagramGraphGroupToMembers/)
  assert.match(designPanelSource, /resetDiagramGraphGroupManualLayout/)
  assert.match(designPanelSource, /laneDirection/)
  assert.match(designPanelSource, /addDiagramChildNode/)
  assert.match(designPanelSource, /addDiagramGraphEdge/)
  assert.match(designPanelSource, /duplicateDiagramGraphNode/)
  assert.match(designPanelSource, /updateDiagramGraphGroup/)
  assert.match(designPanelSource, /removeDiagramGraphGroup/)
  assert.match(designPanelSource, /reverseDiagramGraphEdge/)
  assert.match(designPanelSource, /connectDiagramGraphEdge/)
  assert.match(designPanelSource, /updateDiagramGraphNodePosition/)
  assert.match(designPanelSource, /update:modelValue/)
  assert.match(designPanelSource, /parseSceneDocumentString/)
  assert.match(designPanelSource, /isBoundToDesignResource/)
  assert.match(designPanelSource, /导出 Page PNG/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignFloatingToolbar/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignSidebarPanel/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignShell/)
  assert.doesNotMatch(designPanelSource, /WorkspaceDesignLayersPanel/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignFloatingToolbar/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignSidebarPanel/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignShell/)
  assert.doesNotMatch(workspaceComponentSources, /WorkspaceDesignLayersPanel/)
  assert.match(designCanvasSource, /@node-drag-start=/)
  assert.match(designCanvasSource, /@node-drag=/)
  assert.match(designCanvasSource, /@node-double-click/)
  assert.match(designCanvasSource, /dragFeedback/)
  assert.match(designCanvasSource, /handleKeydown/)
  assert.match(designCanvasSource, /Arrow/)
  assert.match(designCanvasSource, /tabindex="0"/)
  assert.match(designCanvasSource, /X 对齐/)
  assert.match(designCanvasSource, /duplicate-frame/)
  assert.match(designCanvasSource, /delete-frame/)
  assert.match(designCanvasSource, /update-frame-size/)
  assert.match(designCanvasSource, /onResizePreview/)
  assert.match(designCanvasSource, /onResizeCommit/)
  assert.match(designCanvasSource, /open-frame/)
  assert.match(designCanvasSource, /pan-on-scroll/)
  assert.match(designCanvasSource, /zoom-on-pinch/)
  assert.match(designDiagramEditorSource, /WorkspaceDesignDiagramNode/)
  assert.match(designDiagramEditorSource, /WorkspaceDesignDiagramGroupNode/)
  assert.match(designDiagramEditorSource, /@connect=/)
  assert.match(designDiagramEditorSource, /@node-double-click=/)
  assert.match(designDiagramEditorSource, /@node-drag-start=/)
  assert.match(designDiagramEditorSource, /@node-drag=/)
  assert.match(designDiagramEditorSource, /@node-drag-stop=/)
  assert.match(designDiagramEditorSource, /dragFeedback/)
  assert.match(designDiagramEditorSource, /update-node-position/)
  assert.match(designDiagramEditorSource, /update-group-frame/)
  assert.match(designDiagramEditorSource, /onResizeGroup/)
  assert.match(designDiagramEditorSource, /select-group/)
  assert.match(designDiagramEditorSource, /selectedGroupId/)
  assert.match(designDiagramEditorSource, /create-group/)
  assert.match(designDiagramEditorSource, /delete-group/)
  assert.match(designDiagramEditorSource, /New Group/)
  assert.match(designDiagramEditorSource, /New Lane/)
  assert.match(designDiagramEditorSource, /Add Child/)
  assert.match(designDiagramEditorSource, /Duplicate/)
  assert.match(designDiagramEditorSource, /Reverse/)
  assert.match(designDiagramEditorSource, /X 对齐/)
  assert.match(designDiagramEditorSource, /handleKeydown/)
  assert.match(designDiagramEditorSource, /emitNudgeSelection/)
  assert.match(designDiagramEditorSource, /arrowleft/)
  assert.match(designDiagramEditorSource, /Cmd\/Ctrl \+ D/)
  assert.match(designDiagramEditorSource, /tabindex="0"/)
  assert.match(designDiagramEditorSource, /select-node/)
  assert.match(designDiagramGroupNodeSource, /layoutKind/)
  assert.match(designDiagramGroupNodeSource, /startResize/)
  assert.match(designDiagramGroupNodeSource, /onResizeGroup/)
  assert.match(designDiagramGroupNodeSource, /cursor-se-resize/)
  assert.match(designDiagramGroupNodeSource, /@pointerdown.stop.prevent/)
  assert.match(designDiagramGroupNodeSource, /Untitled Group/)
  assert.match(designDiagramNodeSource, /Handle/)
  assert.match(designDiagramNodeSource, /Position.Left/)
  assert.match(designDiagramNodeSource, /cursor-pointer/)
  assert.match(designFrameNodeSource, /frame.kind === 'diagram'/)
  assert.match(designFrameNodeSource, /device_mockup/)
  assert.match(designFrameNodeSource, /device_artboard/)
  assert.match(designFrameNodeSource, /startResize/)
  assert.match(designFrameNodeSource, /cursor-se-resize/)
  assert.match(designFrameNodeSource, /onResizePreview/)
  assert.match(designFrameNodeSource, /onResizeCommit/)
  assert.match(designPanelSource, /useDesignHistory/)
  assert.match(designPanelSource, /useDesignCanvasSelection/)
  assert.match(designCanvasSource, /device_artboard/)

  assert.match(flowTabSource, /importFromMermaid/)
  assert.match(flowTabSource, /importFromMarkdownOutline/)
  assert.match(flowTabSource, /importFromDDL/)
  assert.match(flowTabSource, /importArchitectureFromMetadata/)
  assert.match(flowTabSource, /结构源导入/)
  assert.match(flowTabSource, /导入到画布/)
  assert.match(flowTabSource, /docker-compose/)
  assert.match(flowTabSource, /workspace manifests/)
  assert.match(flowTabSource, /OpenAPI/)

  assert.match(viewStoreSource, /'dashboard', 'meeting', 'members', 'flow', 'design', 'settings'/)

  await assert.rejects(readFile(LEGACY_DESIGN_FLOATING_TOOLBAR_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_SIDEBAR_PANEL_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_SHELL_FILE, 'utf8'))
  await assert.rejects(readFile(LEGACY_DESIGN_LAYERS_PANEL_FILE, 'utf8'))
})

it('画布兼容层和 AI scene 工具已接入 SceneDocument', async () => {
  const tldrawSource = await readFile(TLDRAW_FILE, 'utf8')
  const previewSource = await readFile(SCENE_PREVIEW_FILE, 'utf8')
  const orchestratorSource = await readFile(ORCHESTRATOR_FILE, 'utf8')
  const collabPostSource = await readFile(COLLAB_POST_FILE, 'utf8')

  assert.match(tldrawSource, /WorkspaceScenePreview/)
  assert.match(tldrawSource, /sceneDocumentHasStructuredPreview/)
  assert.match(tldrawSource, /withRuntimeSnapshot/)
  assert.match(tldrawSource, /serializeSceneDocument/)
  assert.match(tldrawSource, /scenePreviewDocument/)

  assert.match(previewSource, /renderCompositionAssetToSvg/)
  assert.match(previewSource, /sceneDocumentFromUnknown/)

  assert.match(orchestratorSource, /name: 'generate_scene_from_text'/)
  assert.match(orchestratorSource, /name: 'generate_schema_from_ddl'/)
  assert.match(orchestratorSource, /name: 'export_schema_to_ddl'/)
  assert.match(orchestratorSource, /name: 'generate_architecture_from_metadata'/)
  assert.match(orchestratorSource, /name: 'generate_architecture_from_repo'/)
  assert.match(orchestratorSource, /scanRepoArchitecture/)
  assert.match(orchestratorSource, /name: 'export_architecture_to_mermaid'/)
  assert.match(orchestratorSource, /view: z\.enum\(\['system_context', 'container', 'dependency_map'\]\)\.optional\(\)/)
  assert.match(orchestratorSource, /exportArchitectureModelToMermaid\(parseJsonValue\(sceneDocument\), view \|\| 'dependency_map'\)/)
  assert.match(orchestratorSource, /name: 'apply_template'/)
  assert.match(orchestratorSource, /name: 'relayout_scene'/)
  assert.match(orchestratorSource, /name: 'generate_device_mockup'/)
  assert.match(orchestratorSource, /name: 'generate_design_page'/)
  assert.match(orchestratorSource, /name: 'generate_design_frame'/)
  assert.match(orchestratorSource, /name: 'generate_diagram_frame'/)
  assert.match(orchestratorSource, /name: 'generate_device_mockup_frame'/)
  assert.match(orchestratorSource, /name: 'export_design_asset'/)
  assert.match(orchestratorSource, /name: 'export_scene_asset'/)

  assert.match(collabPostSource, /drawMode\?: string/)
  assert.match(collabPostSource, /sceneSourceType\?: string/)
  assert.match(collabPostSource, /templateKey\?: string/)
  assert.match(collabPostSource, /editorEngine\?: string/)
  assert.match(collabPostSource, /purpose 仅支持 workflow \/ freeform \/ design \/ notes/)
  assert.match(collabPostSource, /ensureProjectDesignCanvas/)
  assert.match(collabPostSource, /metadata:\s*\{/)
})
