import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { it } from 'vitest'

const WORKSPACE_LEFT_SIDEBAR_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceLeftSidebar.vue')
const WORKSPACE_RESOURCE_MANAGER_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceResourceManagerPanel.vue')
const WORKSPACE_LEFT_RAIL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceLeftRail.vue')
const WORKSPACE_UPLOAD_ASIDE_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceUploadAside.vue')
const WORKSPACE_UPLOAD_PANEL_FILE = resolve(process.cwd(), 'app/components/workspace/WorkspaceUploadPanel.vue')
const WORKSPACE_LEFT_SIDEBAR_STYLE_FILE = resolve(process.cwd(), 'app/assets/styles/workspace-left-sidebar.css')

it('左栏始终保留 WorkspaceLeftRail，并通过 collapsed 控制右侧 panel', async () => {
  const [source, railSource, styleSource] = await Promise.all([
    readFile(WORKSPACE_LEFT_SIDEBAR_FILE, 'utf8'),
    readFile(WORKSPACE_LEFT_RAIL_FILE, 'utf8'),
    readFile(WORKSPACE_LEFT_SIDEBAR_STYLE_FILE, 'utf8'),
  ])

  assert.match(source, /collapsed\?: boolean/, 'WorkspaceLeftSidebar 缺少 collapsed prop')
  assert.match(source, /tabSpacingPreset\?: WorkspaceTabSpacingPreset \| ''/, 'WorkspaceLeftSidebar 缺少标签边距预设入参')
  assert.match(source, /'update:collapsed': \[value: boolean\]/, 'WorkspaceLeftSidebar 缺少折叠态更新事件')
  assert.match(source, /<WorkspaceLeftRail/, 'WorkspaceLeftSidebar 缺少常驻 left rail')
  assert.match(source, /:collapsed="props\.collapsed"/, 'WorkspaceLeftSidebar 未向 left rail 透传折叠态')
  assert.match(source, /<Transition :name="panelContentTransitionName" mode="out-in">/, 'WorkspaceLeftSidebar 缺少按方向切换的左侧模块内容过渡')
  assert.match(source, /panelContentTransitionKey/, 'WorkspaceLeftSidebar 缺少左侧模块内容切换 key')
  assert.match(source, /panelContentTransitionName = ref<'workspace-left-panel-content-forward' \| 'workspace-left-panel-content-backward'>/, 'WorkspaceLeftSidebar 缺少左侧模块内容切换方向状态')
  assert.match(source, /syncPanelTransitionDirection\(moduleId\)/, 'WorkspaceLeftSidebar 未在模块切换时同步动画方向')
  assert.match(source, /workspace-left-panel-content-forward-enter-from/, 'WorkspaceLeftSidebar 缺少左侧模块正向切换动画')
  assert.match(source, /workspace-left-panel-content-backward-enter-from/, 'WorkspaceLeftSidebar 缺少左侧模块反向切换动画')
  assert.match(source, /\.workspace-left-panel-content-forward-enter-from,[\s\S]*transform: translateY\(10px\);/, 'WorkspaceLeftSidebar 左栏正向切换仍不是纵向进入动画')
  assert.match(source, /\.workspace-left-panel-content-backward-enter-from,[\s\S]*transform: translateY\(-10px\);/, 'WorkspaceLeftSidebar 左栏反向切换仍不是纵向进入动画')
  assert.doesNotMatch(source, /\.workspace-left-panel-content-forward-enter-from,[\s\S]*translateX\(/, 'WorkspaceLeftSidebar 左栏正向切换仍保留横向位移')
  assert.doesNotMatch(source, /\.workspace-left-panel-content-backward-enter-from,[\s\S]*translateX\(/, 'WorkspaceLeftSidebar 左栏反向切换仍保留横向位移')
  assert.match(source, /:class="\{ 'workspace-left-panel--hidden': props\.collapsed \}"/, 'WorkspaceLeftSidebar 未改成 class 驱动的左侧 panel 折叠动画')
  assert.match(source, /workspace-left-dock--collapsed/, 'WorkspaceLeftSidebar 缺少折叠宽度样式')
  assert.match(source, /workspace-left-dock--collapsed[\s\S]*flex-basis:\s*var\(--workspace-left-rail-width\);/, 'WorkspaceLeftSidebar 缺少外层 dock 收缩过渡宽度')
  assert.match(source, /workspace-left-dock--compact/, 'WorkspaceLeftSidebar 未为紧凑标签边距提供列表压缩样式')
  assert.match(source, /workspace-left-dock--default/, 'WorkspaceLeftSidebar 未为默认标签边距提供左栏密度类')
  assert.match(source, /workspace-left-dock--relaxed/, 'WorkspaceLeftSidebar 未为宽松标签边距提供左栏密度类')
  assert.match(source, /workspace-left-dock--spacious/, 'WorkspaceLeftSidebar 未为偏大标签边距提供左栏密度类')
  assert.match(source, /workspace-left-panel--hidden/, 'WorkspaceLeftSidebar 缺少左侧 panel 收起状态类')
  assert.match(source, /width: 0;/, 'WorkspaceLeftSidebar 缺少左侧 panel 宽度收起动画')
  assert.match(source, /opacity: 0;/, 'WorkspaceLeftSidebar 缺少左侧 panel 透明度收起动画')
  assert.match(source, /transform: translateX\(-10px\);/, 'WorkspaceLeftSidebar 缺少左侧 panel 位移动画')
  assert.match(source, /type WorkspaceLeftModuleId = 'resource_manager' \| 'meeting' \| 'analysis' \| 'project_config' \| 'issue_center' \| 'upload_center' \| 'notification_center'/, 'WorkspaceLeftSidebar 未声明上传与通知左侧模块')
  assert.match(source, /function switchModule\(moduleId: string, options: \{ allowCollapse\?: boolean \} = \{\}\)/, 'WorkspaceLeftSidebar 未给左栏 tab 提供可控的折叠切换入口')
  assert.match(source, /const notificationCenter = useNotificationCenter\(\)/, 'WorkspaceLeftSidebar 未接入通知中心状态，无法在左 rail 切换时回收通知 drawer 残留状态')
  assert.match(source, /function closeRailOverlays\(options: \{ keepUpload\?: boolean \} = \{\}\)/, 'WorkspaceLeftSidebar 缺少左 rail overlay 统一回收入口')
  assert.match(source, /allowCollapse && !props\.collapsed && !recyclePanelOpen\.value && activeModule\.value === moduleId[\s\S]*emit\('update:collapsed', true\)/, 'WorkspaceLeftSidebar 点击当前左栏 tab 时仍不会收起 panel')
  assert.match(source, /switchModule\(moduleId: string, options: \{ allowCollapse\?: boolean \} = \{\}\) \{[\s\S]*closeRailOverlays\(\)/, 'WorkspaceLeftSidebar 切换模块时未回收通知或上传 aside')
  assert.match(source, /function openRecycleBinPanel\(options: \{ allowCollapse\?: boolean \} = \{\}\)/, 'WorkspaceLeftSidebar 未给回收站入口提供折叠切换入口')
  assert.match(source, /allowCollapse && !props\.collapsed && recyclePanelOpen\.value[\s\S]*emit\('update:collapsed', true\)/, 'WorkspaceLeftSidebar 点击当前回收站入口时仍不会收起 panel')
  assert.match(source, /switchModule\(props\.commandModuleId, \{ allowCollapse: false \}\)/, 'WorkspaceLeftSidebar 在命令面板触发时仍可能误收起左栏')
  assert.match(source, /function handleOpenNotifications\(\) \{[\s\S]*switchModule\('notification_center'\)/, 'WorkspaceLeftSidebar 未将通知入口改成左侧模块切换')
  assert.match(source, /@open-notifications="handleOpenNotifications"/, 'WorkspaceLeftSidebar 未接住通知入口事件')
  assert.match(source, /function openUploadPanel\(options: \{ allowCollapse\?: boolean, syncDrawer\?: boolean \} = \{\}\)/, 'WorkspaceLeftSidebar 未提供上传模块打开入口')
  assert.match(source, /watch\(\(\) => props\.uploadDrawerOpen, \(next, previous\) => \{[\s\S]*openUploadPanel\(\{ allowCollapse: false, syncDrawer: false \}\)/, 'WorkspaceLeftSidebar 未在上传状态打开时切到上传模块')
  assert.match(source, /:upload-active="!props\.collapsed && !recyclePanelOpen && activeModule === 'upload_center'"/, 'WorkspaceLeftSidebar 未向 left rail 透传上传激活态')
  assert.match(source, /<WorkspaceUploadPanel[\s\S]*activeModule === 'upload_center'/, 'WorkspaceLeftSidebar 未渲染上传管理模块内容')
  assert.match(source, /:notification-active="!props\.collapsed && !recyclePanelOpen && activeModule === 'notification_center'"/, 'WorkspaceLeftSidebar 未向 left rail 透传通知激活态')
  assert.match(source, /<WorkspaceNotificationPanel[\s\S]*activeModule === 'notification_center'/, 'WorkspaceLeftSidebar 未渲染通知中心模块内容')
  assert.doesNotMatch(source, /:member-management-active=/, 'WorkspaceLeftSidebar 仍向项目协作入口透传选中态')
  assert.match(source, /@toggle-upload-drawer="handleToggleUploadDrawer"/, 'WorkspaceLeftSidebar 未在上传入口切换时回收通知 aside')
  assert.match(source, /'removeProjectResources': \[resourceIds: string\[\]\]/, 'WorkspaceLeftSidebar 缺少批量删除资源事件透传')
  assert.match(source, /--workspace-left-panel-width:\s*calc\(var\(--workspace-left-dock-width\) - var\(--workspace-left-rail-width\)\);/, 'WorkspaceLeftSidebar 未暴露左栏面板宽度变量供 rail aside 复用')
  assert.match(styleSource, /\.workspace-left-dock--compact \{[\s\S]*--workspace-left-tree-row-min-height:\s*32px;[\s\S]*--workspace-left-tree-indent-step:\s*12px;/, '紧凑档未压缩左栏树行高和缩进')
  assert.match(styleSource, /\.workspace-left-dock--default \{[\s\S]*--workspace-left-tree-row-min-height:\s*36px;[\s\S]*--workspace-left-tree-indent-step:\s*14px;/, '默认档缺少左栏树密度基线')
  assert.match(styleSource, /\.workspace-left-dock--relaxed \{[\s\S]*--workspace-left-tree-row-min-height:\s*40px;[\s\S]*--workspace-left-tree-indent-step:\s*18px;/, '宽松档未放大左栏树行高和缩进')
  assert.match(styleSource, /\.workspace-left-dock--spacious \{[\s\S]*--workspace-left-tree-row-min-height:\s*44px;[\s\S]*--workspace-left-tree-indent-step:\s*20px;/, '偏大档未放大左栏树行高和缩进')
  assert.match(styleSource, /min-height:\s*var\(--workspace-left-upload-row-min-height\);/, '上传行未接入左栏密度变量')
  assert.match(styleSource, /padding:\s*var\(--workspace-left-recycle-row-padding-y\)\s+var\(--workspace-left-recycle-row-padding-x\);/, '回收站行未接入左栏密度变量')
  assert.match(styleSource, /padding:\s*var\(--workspace-left-library-row-padding-y\)\s+var\(--workspace-left-library-row-padding-x\);/, '资料库行未接入左栏密度变量')
  assert.match(railSource, /workspace-left-rail__item--active': !props\.collapsed && item\.id === props\.activeId/, 'left rail 在折叠态仍显示顶部模块选中标识')
  assert.doesNotMatch(railSource, /memberManagementActive\?: boolean/, 'left rail 仍为项目协作入口保留选中态入参')
  assert.doesNotMatch(railSource, /workspace-left-rail__members--active/, '项目协作入口仍保留选中态样式')
  assert.match(railSource, /@click="emit\('openMemberManagement'\)"/, '项目协作入口点击后未继续打开主内容 tab')
})

it('资源管理器删除独立系统资料库分组，只保留导入入口', async () => {
  const [source, styleSource] = await Promise.all([
    readFile(WORKSPACE_RESOURCE_MANAGER_PANEL_FILE, 'utf8'),
    readFile(WORKSPACE_LEFT_SIDEBAR_STYLE_FILE, 'utf8'),
  ])

  assert.match(source, /从系统资料库导入/, '资源添加菜单未保留系统资料库导入入口')
  assert.match(source, /openLibraryModal/, '资源管理器未通过导入弹窗统一承接系统资料库入口')
  assert.match(source, /title="批量管理"/, '资源管理器缺少批量管理入口')
  assert.match(source, /requestProjectResourceBatchMenu/, '资源管理器未提供批量管理菜单入口')
  assert.match(source, /workspace-resource-filter/, '资源管理器缺少类型筛选入口')
  assert.match(source, /requestProjectResourceFilterMenu/, '资源管理器类型筛选未接入统一上下文菜单')
  assert.match(source, /requestProjectResourceFilterMenuByKeyboard/, '资源管理器类型筛选缺少键盘菜单入口')
  assert.match(source, /projectResourceTypeFilterOptions/, '资源管理器缺少动态类型筛选项')
  assert.match(source, /const projectResourceFilterButtonLabel = computed\(\(\) => \{/, '资源管理器缺少筛选入口辅助文案')
  assert.match(source, /icon:\s*'apps'/, '资源管理器筛选菜单缺少“全部类型”图标')
  assert.match(source, /icon:\s*'flowsheet'/, '资源管理器筛选菜单缺少流程图图标')
  assert.match(source, /checked:\s*option\.id === projectResourceTypeFilter\.value/, '资源管理器筛选菜单缺少勾选态')
  assert.match(source, /<span v-if="projectResourceFilterActive" class="workspace-resource-filter__label">/, '资源管理器筛选入口未改成仅在激活时显示文字辅助')
  assert.match(source, /resolveProjectResourceTypeFilterId/, '资源管理器缺少项目资料类型归类逻辑')
  assert.match(source, /isMeetingArtifactResource/, '资源管理器缺少会议资料独立分区归类逻辑')
  assert.match(source, /const meetingNoteResources = computed<Resource\[\]>\(\(\) => \{/, '资源管理器缺少会议纪要分区数据源')
  assert.match(source, /const visibleMeetingNoteResources = computed<ProjectResourceTreeRow\[\]>\(\(\) => \{/, '资源管理器缺少会议纪要分区树列表')
  assert.match(source, /sectionExpanded\.meetingNotes/, '资源管理器缺少会议纪要分区展开状态')
  assert.match(source, /<span>会议纪要<\/span>/, '资源管理器缺少独立的会议纪要分区标题')
  assert.match(source, /暂无会议纪要/, '资源管理器缺少会议纪要分区空状态')
  assert.match(source, /当前筛选：\{\{ projectResourceTypeFilterLabel \}\}/, '资源管理器批量编辑态未展示当前筛选类型')
  assert.match(source, /当前筛选（\$\{projectResourceTypeFilterLabel\}）暂无资源/, '资源管理器缺少筛选空状态文案')
  assert.match(source, /'退出批量编辑' : '进入批量编辑'/, '资源管理器批量管理菜单缺少进入批量编辑入口')
  assert.match(source, /label: '批量上传文件'/, '资源管理器批量管理菜单缺少上传入口')
  assert.match(source, /label: '全部展开'/, '资源管理器批量管理菜单缺少展开入口')
  assert.match(source, /workspace-resource-batch-toolbar/, '资源管理器未渲染批量编辑工具条')
  assert.match(source, /workspace-tree-item__checkbox-input/, '资源管理器批量编辑模式未渲染资源勾选框')
  assert.match(source, /'removeProjectResources': \[resourceIds: string\[\]\]/, '资源管理器缺少批量删除事件')
  assert.match(source, /projectResourcesRefreshing\?: boolean/, '资源管理器缺少项目资料后台刷新态入参')
  assert.match(source, /resourceLibraryRefreshing\?: boolean/, '资源管理器缺少关联资料后台刷新态入参')
  assert.match(source, /useTransientHighlightSet/, '资源管理器未接入一次性新增项高亮 composable')
  assert.match(source, /workspace-tree-block__title-row workspace-tree-block__title-row--sticky/, '资源管理器未将“项目资料”标题行标记为 sticky')
  assert.match(source, /workspace-tree-block__title-row workspace-tree-block__title-row--sticky[\s\S]*<span>关联比赛资料<\/span>/, '资源管理器未将“关联比赛资料”标题行标记为 sticky')
  assert.match(source, /workspace-tree-block__refresh-indicator/, '资源管理器缺少区块级刷新提示')
  assert.match(source, /workspace-tree-item-row--fresh/, '资源树缺少新增资源高亮 class')
  assert.match(source, /workspace-library-item--fresh/, '关联资料列表缺少新增项高亮 class')
  assert.match(source, /const libraryListRef = ref<HTMLElement \| null>\(null\)/, '资源管理器缺少项目资源弹窗列表 ref')
  assert.match(source, /function resetLibraryListScroll\(\) \{[\s\S]*libraryListRef\.value\?\.scrollTo\(\{ top: 0 \}\)/, '资源管理器未在项目资源弹窗中重置列表滚动位置')
  assert.match(source, /watch\(libraryModalVisible, \(next\) => \{[\s\S]*resetLibraryListScroll\(\)/, '资源管理器未在项目资源弹窗开关时回到列表顶部')
  assert.doesNotMatch(source, /toggleSection\('systemLibrary'\)|sectionExpanded\.systemLibrary/, '资源管理器仍保留独立系统资料库分组')
  assert.match(styleSource, /\.workspace-project-add-actions \{[\s\S]*display:\s*inline-flex;[\s\S]*gap:\s*6px;/, '资源管理器头部操作区未为批量管理入口预留并排布局')
  assert.match(styleSource, /\.workspace-resource-batch-toolbar \{/, '资源管理器缺少批量编辑工具条样式')
  assert.match(styleSource, /\.workspace-resource-filter \{/, '资源管理器缺少类型筛选样式')
  assert.match(styleSource, /\.workspace-resource-filter--active \{/, '资源管理器缺少激活筛选样式')
  assert.match(styleSource, /\.workspace-tree-block__title-action \{[\s\S]*border:\s*none;[\s\S]*background:\s*transparent;/, '资源管理器头部图标按钮未切回纯 icon 样式')
  assert.match(styleSource, /\.workspace-resource-filter \{[\s\S]*width:\s*var\(--workspace-left-section-title-action-size\);[\s\S]*border:\s*none;/, '资源管理器筛选入口默认态未收窄为纯 icon')
  assert.match(styleSource, /\.workspace-resource-filter--with-label \{[\s\S]*width:\s*auto;/, '资源管理器筛选入口激活态未允许文字辅助')
  assert.match(styleSource, /\.workspace-resource-filter__label \{[\s\S]*max-width:\s*56px;/, '资源管理器类型筛选标签未改成更窄的文字辅助宽度')
  assert.match(styleSource, /\.workspace-tree-item__checkbox-input \{[\s\S]*accent-color:\s*#3f6ae0;/, '资源管理器批量勾选框未接入统一强调色')
  assert.match(styleSource, /\.workspace-tree-block__title-row--sticky,/, '资源管理器顶级栏标题缺少 sticky 选择器')
  assert.match(styleSource, /\.workspace-tree-block__refresh-indicator \{/, '资源管理器缺少刷新提示样式')
  assert.match(styleSource, /\.workspace-tree-item-row--fresh \{[\s\S]*workspace-left-item-fresh/, '资源管理器缺少资源树新增高亮动画')
  assert.match(styleSource, /\.workspace-library-item--fresh \{[\s\S]*workspace-left-item-fresh/, '资源管理器缺少关联资料新增高亮动画')
  assert.doesNotMatch(styleSource, /\.workspace-tree-item-row--sticky-root/, '资源管理器仍在给资源节点本身挂 sticky 样式')
  assert.match(styleSource, /\.workspace-library-modal \.workspace-library-list \{[\s\S]*padding:\s*4px 0;/, '项目资源弹窗列表缺少滚动容器内边距')
  assert.match(styleSource, /\.workspace-library-item \{[\s\S]*align-items:\s*flex-start;[\s\S]*min-height:\s*52px;/, '项目资源弹窗列表项布局仍然过于拥挤')
  assert.match(styleSource, /\.workspace-library-item__title \{[\s\S]*font-size:\s*13px;[\s\S]*white-space:\s*normal;/, '项目资源弹窗标题仍然只支持单行，容易挤压')
})

it('项目资料区在 ResourceManagerPanel 内改为完整树，并支持拖拽排序', async () => {
  const source = await readFile(WORKSPACE_RESOURCE_MANAGER_PANEL_FILE, 'utf8')

  assert.match(source, /interface ProjectResourceTreeNode \{/, '资源管理器未定义树节点结构')
  assert.match(source, /const projectResourceTree = computed<ProjectResourceTreeNode\[\]>\(\(\) => \{/, '资源管理器未构建真实项目资料树')
  assert.match(source, /const visibleResources = computed<ProjectResourceTreeRow\[\]>\(\(\) => \{/, '资源管理器未将树拍平成可视行')
  assert.doesNotMatch(source, /selectedResources\.slice\(0,\s*10\)/, '资源管理器仍然截断前 10 个资源')
  assert.match(source, /createChildCollaborativeDoc/, '资源管理器未提供子协作文档创建动作')
  assert.match(source, /openChildUpload/, '资源管理器未提供上传到指定节点动作')
  assert.match(source, /buildProjectResourceTreePatchPayload/, '资源管理器未构建拖拽排序 payload')
  assert.match(source, /handleResourceDrop/, '资源管理器未处理树节点拖拽落点')
  assert.match(source, /workspace-tree-dropzone/, '资源管理器未渲染拖拽落点区域')
  assert.match(source, /function resolveTreeDepthOffset\(depth: number\): string \{[\s\S]*--workspace-left-tree-indent-step/, '资源管理器未将树缩进接入左栏密度变量')
  assert.doesNotMatch(source, /Math\.max\(0, row\.depth\) \* 14/, '资源管理器仍写死树缩进像素值')
})

it('左栏结构大纲不再用本地推断结果充当真实大纲', async () => {
  const [sidebarSource, resourceManagerSource] = await Promise.all([
    readFile(WORKSPACE_LEFT_SIDEBAR_FILE, 'utf8'),
    readFile(WORKSPACE_RESOURCE_MANAGER_PANEL_FILE, 'utf8'),
  ])

  assert.match(sidebarSource, /outlineSections\?: WorkspaceOutlineSection\[\]/, 'WorkspaceLeftSidebar 缺少统一结构大纲 section 入参')
  assert.match(sidebarSource, /@locate-outline-item="emit\('locateOutlineItem', \$event\)"/, 'WorkspaceLeftSidebar 未透传统一结构定位事件')
  assert.doesNotMatch(sidebarSource, /workspace-left-sidebar__structural-contract|v-if="false"/, 'WorkspaceLeftSidebar 仍保留旧的占位结构契约')
  assert.doesNotMatch(resourceManagerSource, /const fallbackOutlineItems = computed<OutlineItem\[\]>\(\(\) => \{/, '资源管理器仍保留本地推断大纲 fallback')
  assert.doesNotMatch(resourceManagerSource, /extractResourceOutlineChildren/, '资源管理器仍在从资源正文推断假大纲')
  assert.match(resourceManagerSource, /outlineSections\?: WorkspaceOutlineSection\[\]/, '资源管理器缺少统一结构大纲 section 入参')
  assert.match(resourceManagerSource, /flattenWorkspaceOutlineRows/, '资源管理器未通过统一 outline 行拍平渲染双区块结构')
  assert.match(resourceManagerSource, /workspace-outline-section__title/, '资源管理器未渲染大纲分区标题')
  assert.match(resourceManagerSource, /section\.emptyText/, '资源管理器未按分区渲染空状态')
  assert.match(resourceManagerSource, /emit\('locateOutlineItem', row\.node\)/, '资源管理器未将点击行为收敛到统一定位事件')
})

it('left rail 图标收窄并改成轻量 popover 名称提示', async () => {
  const source = await readFile(WORKSPACE_LEFT_RAIL_FILE, 'utf8')

  assert.match(source, /font-variation-settings:\s*'FILL' 0,\s*'wght' 320,\s*'opsz' 24/, 'left rail 图标未改成轻字重')
  assert.match(source, /workspace-left-rail__popover/, 'left rail 缺少轻量 popover 名称层')
  assert.match(source, /workspace-left-rail__footer-divider/, 'left rail 未在设置与头像菜单之间加入分割线')
  assert.match(source, /<WorkspaceUserRailMenu/, 'left rail 底部缺少头像菜单入口')
  assert.doesNotMatch(source, /workspace-left-rail__item--active::before/, 'left rail 仍保留旧的粗高亮指示条')
  assert.doesNotMatch(source, /record_voice_over/, 'left rail 底部仍保留模拟答辩按钮')
})

it('上传入口已迁移到左侧 rail，并切到左侧 panel 的上传模块', async () => {
  const [sidebarSource, railSource, uploadSource, uploadPanelSource] = await Promise.all([
    readFile(WORKSPACE_LEFT_SIDEBAR_FILE, 'utf8'),
    readFile(WORKSPACE_LEFT_RAIL_FILE, 'utf8'),
    readFile(WORKSPACE_UPLOAD_ASIDE_FILE, 'utf8'),
    readFile(WORKSPACE_UPLOAD_PANEL_FILE, 'utf8'),
  ])

  assert.match(sidebarSource, /uploadSummary\?: ProjectUploadSummary \| null/, 'WorkspaceLeftSidebar 缺少上传摘要入参')
  assert.match(sidebarSource, /uploadDrawerOpen\?: boolean/, 'WorkspaceLeftSidebar 缺少上传抽屉打开态入参')
  assert.match(sidebarSource, /uploadActivityItems\?: ProjectUploadActivityItem\[\]/, 'WorkspaceLeftSidebar 缺少上传活动列表入参')
  assert.match(sidebarSource, /@toggle-upload-drawer="handleToggleUploadDrawer"/, 'WorkspaceLeftSidebar 未接住上传入口切换事件')
  assert.match(railSource, /<WorkspaceUploadAside/, 'WorkspaceLeftRail 未挂载上传 aside 组件')
  assert.match(uploadSource, /data-testid="workspace-left-rail-upload-button"/, '左 rail 上传入口缺少测试锚点')
  assert.match(uploadSource, /active\?: boolean/, '左 rail 上传入口未暴露显式激活态入参')
  assert.match(uploadSource, /:aria-pressed="props\.active \? 'true' : 'false'"/, '左 rail 上传入口未根据模块状态透传激活语义')
  assert.doesNotMatch(uploadSource, /data-testid="workspace-left-upload-drawer"/, '上传入口组件仍在挂载 rail 抽屉')
  assert.doesNotMatch(uploadSource, /workspace-upload-drawer--aside/, '上传入口组件仍保留 rail aside 形态')
  assert.match(uploadPanelSource, /data-testid="workspace-left-panel-upload-module"/, '左侧上传模块缺少稳定测试锚点')
  assert.match(uploadPanelSource, /上传管理/, '左侧上传模块缺少标题')
  assert.match(uploadPanelSource, /最近 7 天暂无上传记录/, '左侧上传模块缺少空状态文案')
  assert.match(uploadPanelSource, /emit\('pauseAllUploadTasks'\)/, '左侧上传模块未复用批量上传操作')
})
