export {
  AuthLoginMeta,
  AuthLoginResult,
  AuthMeResult,
  AuthSession,
  AuthSessionHistoryItem,
  AuthSessionHistoryStatus,
  AuthSessionProbeResult,
  AuthUser,
  CasdoorAuthMeta,
  CasdoorIntegrationConfig,
  OAuthAuthMeta,
  OAuthProtocolMode,
  PlatformPermission,
  PlatformRole,
  PlatformRoleAssignment,
  UserNotification,
  UserNotificationCategory,
  UserNotificationListResult,
  UserNotificationType,
} from './domain-legacy'
